### ISSUE TITLE
Question: using snowstorm to serve SNOMED expressions and annotations

### ISSUE THREAD

**Issue by alexissmirnov** [IHTSDO/snowstorm#100]
Hello,

Would it be appropriate to consider snowstorm for the following use-cases?

1. Storing and serving SNOMED expressions

There's a number of statements that are not defined by any existing (primitive) SNOMED concept, but due to the compositionality, it is possible to express medical statements using expressions. For example, there's no concept to define a statement "allergy to medications is unknown", but can be expressed by the following expression:

```
413350009 |Finding with explicit context (situation)| { 
    246090004 |associated finding| = 416098002 |Allergy to drug (finding)|, 
    408729009 |Finding context (attribute)| = 261665006 |Unknown (qualifier value)| 
}
```

Would it be possible/appropriate to use snowstorm to store such an expression? Ideally, these expressions would be indexed along with the regular (primitive) concepts, so that ECL queries would return them.

2. Is it possible to use snowstorm to store and serve arbitrary attributes assigned to SNOMED concepts and expressions?

Following the example above, imagine a system that would like to present a question to the patient: `"Are you allergic to any medications?"`

It is desirable to store this question along with the concept `416098002 |Allergy to drug (finding)|`, as an attribute. Furthermore, some systems would need other variants of this question (such as "Is your child known to be allergic to any medications?") and stored in multiple languages.

One approach is to think of these questions as attributes to concepts stored/served by snowstorm, and be returned by ECL queries. Is it possible/appropriate to use snowstorm in this way?

**Comment by kaicode** [comment]
This is not yet possible. I will close this ticket due to overlap with #87

**Comment by lihaiming** [comment]
How can I turn off the subscription?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Kai Kewley<mailto:notifications@github.com>
发送时间: 2020年7月16日 21:18
收件人: IHTSDO/snowstorm<mailto:snowstorm@noreply.github.com>
抄送: Subscribed<mailto:subscribed@noreply.github.com>
主题: Re: [IHTSDO/snowstorm] Question: using snowstorm to serve SNOMED expressions and annotations (#100)


This is not yet possible. I will close this ticket due to overlap with #87<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIHTSDO%2Fsnowstorm%2Fissues%2F87&data=02%7C01%7C%7Cab5221af696d4057f67708d8298ab949%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637305023068551304&sdata=7XqQkUtjg2zaF1B7w%2BSB83sQUeQ3EBRKE7DmFNNVetE%3D&reserved=0>

―

**Comment by kaicode** [comment]
@lihaiming try this option:
<img width="1315" alt="Screenshot 2020-07-16 at 14 20 24" src="https://user-images.githubusercontent.com/2010517/87675722-a44c9100-c76f-11ea-9675-43c9497754ea.png">
