### ISSUE TITLE
Too many results causing too costly "There are over 300000 results. Aggregating these results would be too costly." error

### ISSUE THREAD

**Issue by jtart** [IHTSDO/snowstorm#107]
We are hosting a Snowstorm server and a very common search to the `/browser/MAIN/descriptions` endpoint with `lym` as a search term is causing the error in the title to occur.

Is there anything that we can do to fix this issue? `lym` is a very common search term and would not expect it to crach.

We are using these query params:
- conceptActive=true
- offset=0
- limit=50
- term=lym
- groupByConcept=true
- active=true

**Comment by kaicode** [comment]
Hi @jtart,
Have you considered using the `/MAIN/descriptions` endpoint which does not run the costly aggregations? Limiting the results using `semanticTag` is another option.

**Comment by kaicode** [comment]
Also what Edition of SNOMED CT are you using?
The latest International Edition only has 3799 results for this search:
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/descriptions?conceptActive=true&groupByConcept=true&active=true&term=lym

**Comment by jtart** [comment]
@kaicode the `/MAIN/descriptions` can only be searched by concept ID, right? We need descriptions for many different concepts, not descriptions for individual concepts.

**Comment by jtart** [comment]
FYI our issue is with any result that could return many results, e.g. searching for terms with fewer cahracters, `lym` was just an example.

**Comment by jtart** [comment]
@kaicode i think we are using the Jan 2020 UK edition of SNOMED CT.

**Comment by kaicode** [comment]
@jtart Apologies, you are correct `/MAIN/descriptions` endpoint doesn't have the term filter yet.

Would the `GET /{branch}/concepts` may work for your requirements? That function doesn't have any aggregations. The term matching uses all descriptions but only the FSN and PT are returned. This may or may not work?
Example: https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2020-03-09/concepts?activeFilter=true&termActive=true&term=lym

I would not recommend allowing users to search using a term with less than three characters because of performance considerations. 

A great feature which I encourage users to leverage is the multi-prefix any order search. For example "lym no" to find "Structure of lymph node".

If you need the term, active and termActive parameters adding to the `/MAIN/descriptions` let me know, we can sort that.

**Comment by sroze** [comment]
> A great feature which I encourage users to leverage is the multi-prefix any order search. For example "lym no" to find "Structure of lymph node".

How would the API call look like to support this?

**Comment by kaicode** [comment]
Separate prefixes by space, URL encode and use as term parameter. 
E.g.
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2020-03-09/concepts?activeFilter=true&termActive=true&term=lym%20no

**Comment by jtart** [comment]
Hi @kaicode, sorry coming back to this now. We tried a few measures to fix the issues we're having but we're still struggling.

We cannot search by concept as concepts are too a bit too clinical and our users might not be that clinical. We're having issues where searching for very common search terms - i.e. `lymph` - returns too many results from ES for the Snowstorm server to aggregate.

To our interaction with the `descriptions` endpoint, we've added the query parameters that already exist - `active`/`conceptActive - for limiting results to only active concepts and descriptions but still face the same 'too costly to aggregate' errors.

**Comment by jtart** [comment]
@kaicode apologies I misread your comments related to the `descriptions` endpoint(s). What is the difference between the browser and non-browser `descriptions` endpoint? Why does the latter not run aggregations?

**Comment by jtart** [comment]
@kaicode, would it be possible to get `term`, `active` and `termActive` added to `/MAIN/descriptions` endpoint?

**Comment by jtart** [comment]
Hi @kaicode, just reaching out to you one last time, Cc’ing @pgwilliams.

Ideally we would not migrate away from Snowstorm but we are at quite the impasse with this issue and need to move forward.

Any assistance you can provide with the above would be much appreciated.

**Comment by kaicode** [comment]
Hi @jtart,

I'm concerned that something else may be going wrong if you are not able to search for a term such as `lymph`. You say you are exceeding the 300K limit but I'm not sure how. There are 13,814 matches in the latest International Edition (without grouping by concept).
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2020-03-09/descriptions?term=lymph
.. unless you are working with an extension which adds another 280K matches to this search?

The reason we chose the 300K limit was because the International Edition has around 350K active concepts, if a description search with at least three characters is matching more than 300K terms something unexpected must be happening.

Could you share the API call you are making to get the error?

Yes the simple search parameters can be added to the low level description endpoint. We are heads down on other SI priorities at the moment so that would take a couple of weeks.

**Comment by jtart** [comment]
@kaicode the API call we are making is `https://<<snowstorm-server.com>>/browser/MAIN/descriptions?groupByConcept=true&active=true&conceptActive=true&offset=0&limit=50&term=lymph`.

We might well have extensions loaded that are cuaisng the issue. This is what we have loaded:
- UK SNOMED CT Clinical Edition, RF2: Full, Snapshot & Delta
- UK SNOMED CT Drug Extension, RF2: Full, Snapshot & Delta

We might well not need the drug extension - certainly for the calls we are having issues with we do not. Is it possible to exclude certain extensions in a request?

**Comment by jtart** [comment]
I can see that most of our requests come from the module `999000011000001104`, which is a Drug extension 🙂 I can see the `module` query param but it's not available as an array. Is there another option at all?

**Comment by jtart** [comment]
Hi @kaicode, me again! Is there a "Snowstorm way" to just remove extensions?

**Comment by kaicode** [comment]
Making the module query param into an array is a good idea. I'll do that.
You can only remove an extension if you have imported it as a separate code system with its own branch. 

For example if you have UK SNOMED CT Clinical Edition on the `MAIN` branch and UK SNOMED CT Drug Extension on a `MAIN/SNOMEDCT-UK-DRUG` branch you could remove the second branch using the hard delete admin function `DELETE /admin/{branch}/actions/hard-delete`.

I'm guessing this is not the case because if you had them on separate branches you could just query against `MAIN` and avoid the drug content.

That 300K limit is [configurable](https://github.com/IHTSDO/snowstorm/blob/4.8.0/src/main/resources/application.properties#L193). You could try increasing it and see if the performance is acceptable.

**Comment by kaicode** [comment]
Release [4.10.2](https://github.com/IHTSDO/snowstorm/releases/tag/4.10.2) adds multiple module filtering to the description search.

**Comment by kaicode** [comment]
The multi-module query parameter has been added in release 4.11.0. Release 4.12.1 is also now available. As previously mentioned the 300K limit is configurable. Closing this one now.
