### ISSUE TITLE
FHIR $lookup for extensions

### ISSUE THREAD

**Issue by danka74** [IHTSDO/snowstorm#111]
Dear SNOMED,

http://host:8080/fhir/CodeSystem/$lookup?system=http://snomed.info/sct/45991000052106&code=404684003&_format=json

gives:
```
{
resourceType: "OperationOutcome",
issue: [
{
severity: "error",
code: "processing",
diagnostics: "Failed to call access method: org.snomed.snowstorm.fhir.services.FHIROperationException: 'system' parameter must be present, and currently only 'http://snomed.info/sct' is supported. Instead received: 'http://snomed.info/sct/45991000052106'"
}
]
}
```
$lookup is needed e.g. by the FHIR IG Publisher. snowstorm 4.8.0

Regards,
Daniel

**Comment by pgwilliams** [comment]
Thanks Daniel, yes that's clearly wrong.   I'll get on the case, thanks for reporting.

**Comment by pgwilliams** [comment]
Hi Daniel.  A bunch of FHIR work was done last month to support a course that our E&PS team are developing, but the decision was made not to include that code in the 4.8.0 release because the ink was very much still wet and we have no independent testing resource.    Would you be able to work with the 4.9.0-SNAPSHOT build ie what's in the develop branch?    This particular issue was fixed there on 18 March by https://github.com/IHTSDO/snowstorm/commit/674f259c91b5fb6cce40ddd5928d6e77726f76a4

Checking it locally, when I now call:  http://localhost:8080/fhir/CodeSystem/$lookup?system=http://snomed.info/sct/45991000052106&code=404684003

I get back 
`{
resourceType: "Parameters",
parameter: [
{
name: "version",
valueString: "http://snomed.info/sct/45991000052106"
},
{
name: "display",
valueString: "Clinical finding"
},
{
name: "property",
part: [
{
name: "code",
valueString: "effectiveTime"
},
{
name: "valueString",
valueString: "20040131"
}
]
},
{
name: "property",
part: [
{
name: "code",
valueString: "moduleId"
},
{
name: "value",
valueCode: "900000000000207008"
}
]
},
{
name: "designation",
part: [
{
name: "language",
valueCode: "sv"
},
{
name: "use",
valueCoding: {
system: "http://snomed.info/sct",
code: "900000000000013009",
display: "Synonym"
}
},
{
name: "value",
valueString: "kliniskt fynd"
}
]
},`  etc

**Comment by pgwilliams** [comment]
PS I've made json the default when accept headers are received that indicate the call is being made from a web browser, so you don't need the _format parameter if that's how you're testing the call.

**Comment by kaicode** [comment]
Leaving this issue open until the required change is included in a release.

**Comment by danka74** [comment]
I can confirm that this works now:
http://localhost:8080/fhir/CodeSystem/$lookup?system=http://snomed.info/sct/45991000052106&code=427623005&_format=json

However, the FHIR IG Publisher now gives this:

warning	Error from server: Unable to provide support for code system http://snomed.info/sct/45991000052106

Don't know if this is the same issue, cannot find this phrase "Unable to provide support..." in the code...

**Comment by kaicode** [comment]
This fix was released some time ago. Possibly as early as v4.10.2.
