### ISSUE TITLE
MRCM attribute domain not always correct

### ISSUE THREAD

**Issue by hielkema** [IHTSDO/snowstorm#115]
Dear all, we're investigating the MRCM operations to see if we could use them in a postcoordination tool. We were very pleased to find the two MRCM methods which seem tailored for the purpose, but their results don't always match the editorial guide. Part of the discrepancies seem to stem from the MRCM reference sets (such as attributeInGroupCardinality 0...1 for attributes which shouldn't be grouped at all), but I also think there's a bug in GET /mrcm/{branch}/domain-attributes.

243796009 |situation with explict context| is in the domain of two attributes (temporal context & subject relationship context). Its child 413350009 |Finding with explicit context| is in the domain of two additional attributes (finding context & associated finding); its other child 129125009 |Procedure with explicit context| is in range of two other attributes (procedure context & associated procedure).

According to the domain-attributes however, a situation with context is in the domain of all 6 attributes. So it would validate a postcoordination with both an associated finding ánd an associated procedure, which is a violation of the editorial guidelines. I checked in the MRCM reference sets, and they specify that the domain of 'finding context' is 413350009 |Finding with explicit context|, as it should be. So why does domain-attributes return it as a valid attribute for 243796009 |situation with explict context|?

**Comment by kaicode** [comment]
Hi @hielkema, thanks for raising the issue. I'm glad you are taking advantage of the new Snowstorm MRCM API which supports post-coordination!

Please note that the Editorial Guide should be consistent with the latest published MRCM reference sets but the guide only covers pre-coordinated content. There is no Editorial Guide for post coordinated content although the MRCM does cover it.

You are getting both _"Finding context (attribute)"_ and _"Procedure context (attribute)"_ when specifying a parent of _243796009 "Situation with explicit context (situation)"_ because proximal primitive modeling is the default modeling style. 

With this style of modeling the SNOMED content author specifies a higher level parent concept then supplies enough attributes for the classification process (OWL reasoner) to assign the best inferred parent. In this case the MRCM specifies that a broader scope of attributes should be provided up front to allow all the relatant attributes to be given before a more specific parent (which may be in a more specific domain) is found by the classifier.

Proximal primitive modeling is used by the authors of the International Edition and ideally it is recommended for post coordinated content. Post coordinated would then need to be classified to find the best parent concept before being used for data analysis tasks. SNOMED International provide the [Classification Service](https://github.com/IHTSDO/classification-service) which uses an OWL reasoner (ELK) to infer is-a relationships and also produces the necessary normal form (inferred relationships). This is in production use for pre-coordinated concepts and should work for post-coordinated content too given the right inputs.

If you would not like to use proximal primitive modeling simply set the _proximalPrimitiveModeling_ flag to _false_ then the attributes from the more specific MRCM domains will not be returned.

- Request for attributes for "Situation with explicit context (situation)" post-coordinated expression **using proximal primitive modeling**: 
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/mrcm/MAIN/2020-03-09/domain-attributes?contentType=NEW_PRECOORDINATED&parentIds=243796009&proximalPrimitiveModeling=true
**Returns 7 attributes** including those from _"Procedure with explicit context (situation)"_ and _"Finding with explicit context (situation)"_

- Request for attributes for "Situation with explicit context (situation)" post-coordinated expression **without proximal primitive modeling**: 
https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/mrcm/MAIN/2020-03-09/domain-attributes?contentType=NEW_PRECOORDINATED&parentIds=243796009&proximalPrimitiveModeling=false
**Returns just 3 attributes**.

I hope that helps!

Kind regards,
Kai

**Comment by mertenssander** [comment]
Thanks for this elaborate answer @kaicode !
