### ISSUE TITLE
When will Elasticsearch 7 support be available?

### ISSUE THREAD

**Issue by sanjitvimal** [IHTSDO/snowstorm#116]
I want to upgrade the snowstorm to elasticsearch version 7.6.0.
Any guideline is available or any specific version which is compatible with 7.6.x?

**Comment by kaicode** [comment]
Hi @sanjitvimal,

I'm sorry right now Snowstorm is only compatible with Elasticsearch version 6.x.x (we recommend 6.8.x.). The Elasticsearch client within the codebase will not work with version 7.

We will be upgrading Snowstorm's Elasticsearch dependency to version 7 in the next few months well before the [Elasticsearch 6.8.x end of life date which is 2020-11-20](https://www.elastic.co/support/eol).

Keep an eye out Snowstorm 5.x in the next three or four months which will have this feature.

**Comment by alex-ha-github** [comment]
Hi @kaicode 

Does it have any update strategy on supporting latest Elasticsearch version?
e.g. Update will be available at least two months before the Elasticsearch version EOL.

**Comment by kaicode** [comment]
@rorydavidson are you able to provide any more information on the scheduling of this work?

**Comment by rorydavidson** [comment]
This is on our roadmap for this year, aiming to be done before support for ES v6.x finishes on 2020-11-20

**Comment by kaicode** [comment]
We are working on the Elasticsearch 7 upgrade now. We are aiming to deploy it into our production environments at the beginning of September.

At the moment we are targeting Elasticsearch `7.4.x` because this is the latest version available in AWS ES which is a common deployment requirement.
<img width="855" alt="Screenshot 2020-07-10 at 15 42 00" src="https://user-images.githubusercontent.com/2010517/87166784-f56a0a00-c2c3-11ea-9d7a-789e8bba50b2.png">

Snowstorm 5.x will have this change clearly marked in the release notes and change log. I will not post the release on the project release page until our testing is complete.

**Comment by rorydavidson** [comment]
Closing this issue as the current production release, https://github.com/IHTSDO/snowstorm/releases, now supports Elasticsearch v7.7.
