### ISSUE TITLE
Option to return identifier array rather that complete concepts for findConcept 

### ISSUE THREAD

**Issue by dmarkwell** [IHTSDO/snowstorm#135]
The findConcepts function is very powerful and flexible. However, for some use cases it would be really useful have a "ids only" option that returns a simple array of concept identifiers rather than the full set of data for each concept. Ideally this option would be fast enough not to require paging or at least to support much larger page sizes. This would allow all conformant concept identifiers to be rapidly and simply accessed.

**Example:**
An application needs to analyse a large volume of EHR data (millions of record items). To produce the required report, it needs to test each record item data against several different sets of criteria each of which includes an ECL constraint.
Calling the findConcept method to perform each test is not a realistic option from a performance issue. Instead the application wants to get the identifiers of all concepts that match each ECL constraint so these can be directly tested against the stored data.
This is possible using the current findConcepts function but for each matching concept a lot additional data (which is not required for this use case) is returned along with the identifier. This probably has an impact on performance ... at least in terms of the larger volume of data returned. Also the need for paging might be removed by reducing the volume of returned data which would simplify use.

**Note:**
A quick test suggests that the volume of data returned drops to substantially. In one test a constraint returning a set of 10,000 disorder concepts returned 3.9Mb which when reduced to an array resulted in a 96Kb file.

**Comment by kaicode** [comment]
Hi @dmarkwell, nice to hear from you.

I like this idea. I would like to make Snowstorm as fast and efficient as possible for a range of tasks including bulk work and fulfilling SNOMED queries for data analytics.

I'll have a go at implementing this to see what performance improvement we get. We are already fetching the descriptions and lang refsets in bulk for all results so the fact that we have descriptions should not have minimal effect on the response time, however the smaller response byte size is a nice to have.

With regards the pagination, there are limits within Elasticsearch which makes serving pages larger than 10K in size inefficient. To fetch the next 10K results please use the search_after parameter, you will find the value for this at the end of the previous page. This lets Elasticsearch jump to the first result you want and grab the next 10K rather than loading the first N x 10K results into memory when they are not required in the response.

I'll have a go at this over the next couple of weeks and take some measurements.

**Comment by kaicode** [comment]
Initial findings in our development environment show that fetching the first 10K ECL results with concept identifier, FSN and PT takes between 5 and 9 seconds then another couple of seconds to download the results.
Fetching the same results and returning just an array of concept identifiers takes 500-1,400 milliseconds including the query and content download.
This is clearly a dramatic performance increase when fetching a large results set. 

I have updated the `GET /{branch}/concepts` endpoint with a `returnIdOnly` parameter to enable this feature. 

The 10K page size limit must still be in place. Each response contains a `searchAfter` token which can be used to fetch the next 10K results. In this way there is no limit to the number of results which can be fetched in 10K sized chunks.

This feature has missed the release candidate for 4.12.x which is due to be deployed in our systems today but I will create a new release with this feature in the next one or two weeks. This will be version 4.13.x.

Thank you for a great suggestion @dmarkwell !

**Comment by kaicode** [comment]
Implemented in [release 4.13.0](../releases/tag/4.13.0).
