### ISSUE TITLE
Snowstorm launch issue - /tmp/spring.log file

### ISSUE THREAD

**Issue by vachonr** [IHTSDO/snowstorm#138]
Hello

Hi have an issue (see the attached field) when I launch the following command:

java -Xms2g -Xmx4g -jar ./Snowstorm/snowstorm-4.10.2.jar --delete-indices -import ./SNOMapping/Snomed/SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip --exit >snowstorm_4_10_2_launch.log

[snowstorm_4_10_2_launch.log](https://github.com/IHTSDO/snowstorm/files/4902337/snowstorm_4_10_2_launch.log)

Thanks by advance for your help

**Comment by kaicode** [comment]
Hi @vachonr, thanks for reaching out. If you are having this issue others are probably seeing the same thing in some cases.

The Spring Boot framework is attempting to create a log file under `/tmp/spring.log`. I have noticed this before as it prevents running multiple instances of Snowstorm on the same machine but I have not yet implemented a solution. 

In most environments this is okay because applications generally have write access to /tmp/ however in your environment it looks like this is restricted for this application.

The easy fix would be to create the file `/tmp/spring.log` and grant the application write access to that file.
Alternatively it should be possible to configure Spring Boot to write to another file location or disable this completely. 

We use system out and system error to capture output from Snowstorm because this method is environment independant. For example Supervisor in Ubuntu can be used to redirect system out and error to logging log files. So this file is not really needed.

I will raise an issue to remove the need for this file but I hope this ticket can be resolved via one of the suggested workarounds.

Kind regards,
Kai

**Comment by kaicode** [comment]
@vachonr I also noticed that there is only one hyphen in your run command for the `--import` argument. That needs two hyphens otherwise the RF2 import will not start.

**Comment by vachonr** [comment]
Thanks Kai

I created a file spring.log in the directory tmp. But I have same error message.

tmp has the following right:

[cid:image002.png@01D656CF.60847200]


I have created the spring.log file with the following right:

[cid:image001.jpg@01D656D1.1C726160]


I can’t also configure Spring Boot, because the generation of the .jar failed. I think I have not the permission to generate this file.

Do you think the right I gave to the directory and the .log file are sufficient ?

Regards.


René


De : Kai Kewley <notifications@github.com>
Envoyé : vendredi 10 juillet 2020 12:23
À : IHTSDO/snowstorm <snowstorm@noreply.github.com>
Cc : VACHON Rene <rene.vachon@biomerieux.com>; Mention <mention@noreply.github.com>
Objet : Re: [IHTSDO/snowstorm] Snowstorm launch issue (#138)


External Email

Hi @vachonr<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fvachonr&data=01%7C01%7Crene.vachon%40biomerieux.com%7C34dd194911b542d6e6a508d824bb4008%7Caec0543acc734fa49e2acf52adf9b788%7C1&sdata=UeceEtbP4pLhEjV32q8VwuIQvE2G7HxDcybkTckKiRE%3D&reserved=0>, thanks for reaching out. If you are having this issue others are probably seeing the same thing in some cases.

The Spring Boot framework is attempting to create a log file under /tmp/spring.log. I have noticed this before as it prevents running multiple instances of Snowstorm on the same machine but I have not yet implemented a solution.

In most environments this is okay because applications generally have write access to /tmp/ however in your environment it looks like this is restricted for this application.

The easy fix would be to create the file /tmp/spring.log and grant the application write access to that file.
Alternatively it should be possible to configure Spring Boot to write to another file location or disable this completely.

We use system out and system error to capture output from Snowstorm because this method is environment independant. For example Supervisor in Ubuntu can be used to redirect system out and error to logging log files. So this file is not really needed.

I will raise an issue to remove the need for this file but I hope this ticket can be resolved via one of the suggested workarounds.

Kind regards,
Kai

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIHTSDO%2Fsnowstorm%2Fissues%2F138%23issuecomment-656602920&data=01%7C01%7Crene.vachon%40biomerieux.com%7C34dd194911b542d6e6a508d824bb4008%7Caec0543acc734fa49e2acf52adf9b788%7C1&sdata=bm2bV3ALcnwoMJW9ymVIHYnaAoIBpXI%2BEAc3N4zlVlA%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FALB2VV7MOQO32DT3FZFK7SDR23TY3ANCNFSM4OWN2QUQ&data=01%7C01%7Crene.vachon%40biomerieux.com%7C34dd194911b542d6e6a508d824bb4008%7Caec0543acc734fa49e2acf52adf9b788%7C1&sdata=ZdxuedBCnbGEqXCvUeywYIfZqCStIvMDmGBUwxptNoY%3D&reserved=0>.


AVIS : Ce courrier et ses pieces jointes sont destines a leur seul destinataire et peuvent contenir des informations confidentielles appartenant a bioMerieux. Si vous n'etes pas destinataire, vous etes informe que toute lecture, divulgation, ou reproduction de ce message et des pieces jointes est strictement interdite. Si vous avez recu ce message par erreur merci d'en prevenir l'expediteur et de le detruire, ainsi que ses pieces jointes.

NOTICE: This message and attachments are intended only for the use of their addressee and may contain confidential information belonging to bioMerieux. If you are not the intended recipient, you are hereby notified that any reading, dissemination, distribution, or copying of this message, or any attachment, is strictly prohibited. If you have received this message in error, please notify the original sender immediately and delete this message, along with any attachments.

**Comment by kaicode** [comment]
Hi René,

I'm sorry I don't seem to be able to see your screenshots in email or in github but this may not matter. 

There is a way to use an alternative tmp directory which may be the best workaround here. Simply create a `temp` directory in the same directory as the Snowstorm application then use `-Djava.io.tmpdir=temp` before the `-jar` in the `java` command when starting Snowstorm. This will cause Spring Boot to write the `spring.log` file under `temp` instead which should get around the permissions issue.

Modified version of the command you provided:
`java -Xms2g -Xmx4g -Djava.io.tmpdir=temp -jar ./Snowstorm/snowstorm-4.10.2.jar --delete-indices --import ./SNOMapping/Snomed/SnomedCT_InternationalRF2_PRODUCTION_20200309T120000Z.zip --exit >snowstorm_4_10_2_launch.log`

I hope that helps.

Kind regards,
Kai

**Comment by vachonr** [comment]
Thanks Kai

It works better now, but I think that we have a problem with elasticsearch as you can see in the following log file:

[snowstorm.log](https://github.com/IHTSDO/snowstorm/files/4903964/snowstorm.log)

Best regards,

René

**Comment by vachonr** [comment]
Sorry I didn't want to close

**Comment by kaicode** [comment]
Check your Elasticsearch instance is still up by making a request to http://localhost:9200
It looks like it is up to start with because Snowstorm successfully sets up the indices but then Elasticsearch starts returning a `503 Service Unavailable` error. Elasticsearch may not have enough memory or disk space. Check the Elasticsearch logs.

**Comment by vachonr** [comment]
Thanks
It works now.
