### ISSUE TITLE
Querying descriptions of several concepts in GET {branch}/descriptions

### ISSUE THREAD

**Issue by peterdutey** [IHTSDO/snowstorm#142]
Hello

This may be a little naive, but have you considered enabling users to fetch descriptions of several concepts?

This would imply an array `concept` argument to [findDescriptions](https://github.com/IHTSDO/snowstorm/blob/07e3f7ea08f8091b20f856a4775f867608961329/src/main/java/org/snomed/snowstorm/rest/DescriptionController.java#L150), in a similar way as for [findConcepts](https://github.com/IHTSDO/snowstorm/blob/07e3f7ea08f8091b20f856a4775f867608961329/src/main/java/org/snomed/snowstorm/rest/ConceptController.java#L77)?

This can be very useful for named entity recognition of a narrow field of concepts. In those situations it makes sense to extract all synonyms for the target concepts.

I hope the above makes sense! 
Many thanks in advance
Peter

**Comment by kaicode** [comment]
Yes, nice idea. A workaround would be to use findConcepts and grab the active descriptions from the response but I agree this would be nice to have.

**Comment by jbarcas** [comment]
What would be the expected behaviour here? Replace the single `conceptId` query param to a collection of `conceptIds`? I assume the response should return plain descriptions (the same response as now), such that:
* an empty collection of `conceptIds` would return all descriptions.
* a collection of existing `conceptIds` would return all the descriptions binded to such `conceptIds`.
* a collection of unexistent `conceptIds` would retrn empty collection.

Cheers!
Jesús.

**Comment by peterdutey** [comment]
Yes, and as far as I know this is consistent with the behaviour of findConcepts as well, which is good.
Thanks!
Peter

**Comment by jbarcas** [comment]
yep, I agree that consistency in input params is a plus.

@kaicode you can assign me the issue if you want,

Regards,
Jesús.

**Comment by kaicode** [comment]
@jbarcas please keep the existing `conceptId` param for backward compatibility, in addition to the new `conceptIds`. Breaking API changes should only be made in new major versions of the API. Thank you 😄

**Comment by jbarcas** [comment]
yup, totally agree, updated!

**Comment by kaicode** [comment]
Fixed in [5.0.6](https://github.com/IHTSDO/snowstorm/releases/tag/5.0.6).
