### ISSUE TITLE
Upload Subset of SNOMED CT

### ISSUE THREAD

**Issue by MahboobehJannesari** [IHTSDO/snowstorm#152]
I am in middle of installation snowstorm, I have some questions, 
for loading snomd ct, Can I load refset  or subset of snomed ct instead of snomed ct in Loading section?
How can I customize or build a reference set? is there any tool?

**Comment by kaicode** [comment]
The Snowstorm setup requires at least one complete SNOMED CT edition to be loaded because this contains all the concepts, descriptions and relationships to support search and semantic queries using ECL. 
Each edition and extension contains reference sets which can be queried using the Snowstorm API or using the `^` notation in ECL.

The Snowstorm API has basic support for creating and maintaining reference sets. Once you have an Edition loaded take a look at the Refset Members section of the Swagger API documentation, available under http://localhost:8080/ once the server is up and running. Feel free to raise another issue if you have any specific questions on reference set maintenance.

Depending on your requirements there is also a full [reference set maintenance tool](https://github.com/IHTSDO/ihtsdo-refset-management-service) available.

Kind regards,
Kai Kewley
