### ISSUE TITLE
How can I get descriptions with type TEXT_DEFINITION through FHIR endpoint?

### ISSUE THREAD

**Issue by mvdzel** [IHTSDO/snowstorm#173]
In the Netherlands we have descriptions with type TEXT_DEFINITION.
How can these be queried through the FHIR endpoint?
And related to this, how are all SCT aspects mapped to FHIR resources, is this documented?
@mertenssander

**Comment by pgwilliams** [comment]
Hi Michael.   Text Definitions are treated just like other descriptions so they're included when you get the default properties back.  For example if you do a lookup like:   https://browser.ihtsdotools.org/snowstorm/snomed-ct/fhir/CodeSystem/$lookup?code=868233001

You'll get a block of json that includes:  

![image](https://user-images.githubusercontent.com/6103623/96882781-9053b200-1477-11eb-8995-776071abc11a.png)

**Comment by pgwilliams** [comment]
On the question of how all the various features of SNOMED CT appear in FHIR, no I don't think that's all documented in one place.   It's perhaps a misuse of the ConceptMap$translate operation for example, that it can be used to return historic associations.   There are a few properties specified here that may be of interest:  http://build.fhir.org/snomedct.html#props   a favourite of mine is the NormalForm property which lets you return all the attributes for a concept, albeit as an expression but at least the model is accessible.

**Comment by mertenssander** [comment]
Hi @pgwilliams @mvdzel ,

I have tested this on our dev server, and seem to get inconsistent results. I have to admit I'm fairly new to the FHIR implementation in Snowstorm - so it is very possibly just my inexperience.

- https://snowstorm.test-nictiz.nl/MAIN%2FSNOMEDCT-NL/descriptions?conceptId=22298006
Does provide us with a description with ID 11061321000146118 ("Het (risico op het) afsterven van een deel van de hartspier door onvoldoende toevoer van zuurstofrijk bloed.").
- https://snowstorm.test-nictiz.nl/fhir/CodeSystem/$lookup?code=22298006
Does not.

This description is from the patient friendly language refset, 15551000146102 |Patiëntvriendelijk-Nederlandse taalreferentieset (foundation metadata concept)|, and resides in the 15561000146104 |SNOMED CT Dutch module for patient-friendly descriptions (core metadata concept)| . Could that perhaps be the issue?

**Comment by pgwilliams** [comment]
I'm afraid I'm out of time for today, but just to give you some early thoughts:   The module id is used to do the lookup of the branch and I would normally expect that to go to the most recently published branch, rather than the 'work in progress' which is your MAIN/SNOMEDCT-NL

I don't think you've configured a whole separate branch for module 15561000146104 so that lookup would fail.   Yes, you get "No code system known with default module of 15561000146104" so that's expected.

We coded something of a hack to allow FHIR calls to use 'MAIN' or whatever the working branch for an extension is, so you'll see your Text Definition come back if you include unversioned content:  https://snowstorm.test-nictiz.nl/fhir/CodeSystem/$lookup?code=22298006&version=http://snomed.info/sct/11000146104/version/UNVERSIONED    to force the use of the MAIN/SNOMEDCT-NL branch.

So it seems like something isn't recognizing the branch for 2020-09-30 as the latest one.   This might be a problem in our FHIR lookup, because your metadata for that CodeSystem instance looks fine: https://snowstorm.test-nictiz.nl/codesystems

**Comment by mvdzel** [comment]
I have tried the suggested hack on my own version of snowcloud, but it fails and I don't know were to start looking.
"No code system known with default module of 11000146104"
And I know for sure I did load that module. How can I check that?

**Comment by mertenssander** [comment]
Hi @mvdzel ,
Not that I assume to know the answer, but I though of one potential issue; how did you organize your server? My dev server is organized with the international edition in MAIN, and the dutch extension + patient friendly terms + GMDN mapping in MAIN/SNOMEDCT-NL.

**Comment by kaicode** [comment]
FYI Snowstorm has configuration to map between the FHIR URI module number and the native Snowstorm code system. The defaults can be found in the [application.properties](https://github.com/IHTSDO/snowstorm/blob/7.12.0/src/main/resources/application.properties#L197) file under `codesystem.config`.
