### ISSUE TITLE
Validating ECL expressions

### ISSUE THREAD

**Issue by omershk** [IHTSDO/snowstorm#184]
Hello,

I'm building a python script that sends ECL queries to the snowstorm server. When an invalid query is passed to the server an error is raised and the script aborts. What is the easiest way to verify the integrity of an ECL expression prior to sending it to the snowstorm server?

Thank you in advance,
Omer Shkedi.

**Comment by kaicode** [comment]
Hi Omer,
There are two reasons an ECL query may return an error:
- If the ECL syntax is invalid 
- or if concepts within the ECL are not active on the branch you are querying against.

## Syntax validation
Basic ECL queries take one of these formats:
- `id`
- `id id*`
- `id id* AND id id*`
- `id id* OR id id*`
- `id id* MINUS id id*`

But there are many more variations. A good set of examples can be found in [section 6](https://confluence.ihtsdotools.org/display/DOCECL/6.+Examples) of the [ECL guide](http://snomed.org/ecl).

The [ECL language syntax specification](https://confluence.ihtsdotools.org/pages/viewpage.action?pageId=28739405) and a [Java based parser](https://github.com/IHTSDO/snomed-ecl-parser) are also available. I don't have any useful suggestions of how they could be used from Python.

## Concept active checking
To check that the concepts within the ECL are active you could:
- Load a list of active concepts into your script by loading the concept RF2 file from the SNOMED CT release archive.
- Alternatively you could make a call to the Snowstorm API `GET /{branch}/concepts` endpoint using the `activeFilter=true` and `conceptIds=[list of ids]`. Concepts which are missing or not active will not be returned. Bear in mind the GET request can only take a limited number of concept ids because the length of the whole URL is limited by the HTTP specification. Concepts found as not active using this method could be reported to a user and could be cached in the script.
- Otherwise you could just make a call to the concept search endpoint with the ECL query as you are already. You will get a list of the missing or inactive concepts in the HTTP response:
```
{
  "error": "BAD_REQUEST",
  "message": "Concepts in the ECL request do not exist or are inactive on branch MAIN: 195117009."
}
```

Tip: If your script does not require concept terms/descriptions use the `returnIdOnly=true` flag for much faster ECL execution.

I hope this helps,
Kai

**Comment by danka74** [comment]
@omershk , I would just catch the exceptions in the script and let snowstorm manage the complexity of ECL!
https://docs.python.org/3/tutorial/errors.html#handling-exceptions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch
etc.

**Comment by omershk** [comment]
@kaicode and @danka74 thank you for your answers!
I've followed @danka74's advice and used exceptions to handle these errors but I'll definitely try to implement a parser later like @kaicode suggested.

**Comment by kaicode** [comment]
Parsing the ECL and checking that the concepts are active is not expensive for Snowstorm to do so I agree that just letting Snowstorm handle it is a good option. 

Bear in mind that the ECL language syntax specification is not water tight. There are ECL expressions that are valid according to the syntax but do not execute as expected because they are not terminated correctly or are ambiguous.
Example of bad ECL:
```
< 404684003 | Clinical finding (finding) AND < 272379006 | Event (event) |
```
This should return nothing but when run against Snowstorm this returns all clinical findings because in the pipe after the "Clinical finding (finding)" term is missing so the second clause of the expression is not used.
