### ISSUE TITLE
RF2 export from branch

### ISSUE THREAD

**Issue by Tannjorn** [IHTSDO/snowstorm#217]
When using RF2 export, exporting Delta from a newly created brach, Snowstorm seems to include all components posted to this branch AND all unpublished components from the underlying branches.

The use case is this:

The Snowstorm is set up with MAIN as the international release.

MAIN/SNOMEDCT-NO contains the extension DailyBuild.

Then we post new components to MAIN/SNOMEDCT-NO/[any named branch] using the REST APIs

Finally I would like to export the content in [any named branch] to an RF2, as this is the only way to move content from one Snowstorm to another - first doing an export, then an import.

But creating the RF2 seems to include the extension DailyBuild from SNOMEDCT-NO. Is there any way to avoid this?

**Comment by kaicode** [comment]
Hi @Tannjorn,

Yes by default the DELTA type export includes all unversioned content visible on the selected branch, regardless of where those components were authored.

There is a new export feature being developed to select just the content which was created or promoted to the current branch. This selection does not include components which are visible because they exist on parent branches. The feature is in the master branch and will be included in the `6.0.2` release which will be available next week. The flag in the export configuration to enable this behaviour will be `unpromotedChangesOnly=true`.

**Comment by kaicode** [comment]
Closing as answered.
