### ISSUE TITLE
Snomed procedures name Irish text spelling

### ISSUE THREAD

**Issue by kandascan** [IHTSDO/snowstorm#243]
Hello, I successfully loaded International edition to Snowstorm API, also included there new import for delta.

NEW IMPORT FOR INTERNATIONAL RELEASED: (windows cmd not working use git bash instead)
curl -X POST --header 'Content-Type: multipart/form-data' --header 'Accept: application/json' -F file=@SnomedCT_ManagedServiceIE_PRODUCTION_IE1000220_20201021T120000Z.zip  'http://localhost:8080/imports/f275c255-5c0b-4e73-823f-9f036e36b996/archive'

CHECK STATUS FOR NEW IMPORTS:
http://localhost:8080/imports/839082e0-da2f-42aa-8f4b-28d2155a029c

Loaded completed.

but when I check the procedures using this endpoint 
http://localhost:8080/MAIN/concepts?ecl=%3C71388002&offset=0&limit=1000
I see the procedure names are wrong, it should be Irish names insted of American.
For example:
![image](https://user-images.githubusercontent.com/15519926/111154964-1a6df580-8594-11eb-871f-67822fa231ad.png)

as you can see on the search box you can type: "caesaren" and you can got "cesaren" results.
Thanks for helps.

**Comment by kaicode** [comment]
Hi @kandascan I can see in your ECL search results that the US preferred term is in the results and you would like to see the Irish preferred term, for example `Postmortem caesarean section` for the concept `236990004 | Postmortem cesarean section (procedure) |`. This description has been marked as preferred in the Irish language reference set so as long as the content is loaded you should be able to request that dialect..

There are two reasons why you may not be getting the terms you would like:
1. The branch you are querying may not contain the descriptions you want. You are querying the `MAIN` branch but you may have loaded the IE extension onto another branch, for example `MAIN/SNOMECT-IE` (or preferably use a release branch like `MAIN/SNOMEDCT-IE/2020-10-21`
2. The request `Accept-Language` header has not been set to match the language and language reference set you would like. In your case you are getting the correct language but not the correct dialect/language reference set. Using an `Accept-Language` header like this:`en-X-21000220103,en-X-900000000000509007`. This header will state that is an Irish term is available it should be used, otherwise if an Irish term is not available the US term should be used. I've tested this on the public Snowstorm `MAIN/SNOMEDCT-IE/2020-10-21` branch and it returns Irish preferred terms in the ECL results.

Finally in the screenshot you provided you show the `Cesarean section (procedure)` concept loaded in the browser. The text underlined in red is the FSN of the concept which has not been replaced or translated in the IE extension. That is why it has a US spelling. The FSN of a concept does not usually get translated, usually just the PT (preferred term) is translated or localised. If you needed that text to show the Irish term you would have to update the HTML code in your version of the browser.

I hope that helps.

Kind regards,
Kai Kewley

**Comment by kandascan** [comment]
Hello Kai,

I try to reach this endpoint 
http://localhost:8080/browser/MAIN/concepts/236990004 
to see what I recieved with setting language on the request header like you preferred
{
  "Accept": "application/json",
  "Accept-Language": "en-X-21000220103,en-X-900000000000509007"
}

I got the respond like this:
{
  "conceptId": "236990004",
  "fsn": {
    "term": "Postmortem cesarean section (procedure)",
    "lang": "en"
  },
  "pt": {
    "term": "Postmortem cesarean section",
    "lang": "en"
  },
...
}
but on the description section:
"descriptions": [
.....    
,
    {
      "active": true,
      "moduleId": "900000000000207008",
      "released": true,
      "releasedEffectiveTime": 20170731,
      "descriptionId": "355218015",
      "term": "Postmortem caesarean section",
      "conceptId": "236990004",
      "typeId": "900000000000013009",
      "acceptabilityMap": {
        "900000000000508004": "PREFERRED"
      },
      "type": "SYNONYM",
      "lang": "en",
      "caseSignificance": "CASE_INSENSITIVE",
      "effectiveTime": "20170731"
    },
.....
}

I see the term name what I am looking for "term": "Postmortem caesarean section"
Is there any way to get the term name get at the top of respond on the "fsn" or "pt" section ?
"fsn": {
    "term": "Postmortem cesarean section (procedure)",
    "lang": "en"
  },
  "pt": {
    "term": "Postmortem cesarean section",
    "lang": "en"
  },

I loaded everything again with docker container but still it's working like in a past.

I create application to calling swagger endpoint to get all the data and save into js file for populated search dropdown list, and with respond I got from swagger API i extracted only conceptId and "pt" "term". 
So that is the reason why I am looking for Irish name on "pt" "term" section.
My final fill with extracting data looks like this:
{ value: 236990004, label: "Postmortem cesarean section" }

Thanks for any help
Best
Boguslaw Boczkowski

**Comment by kaicode** [comment]
Hi there,

It looks like the branch you are using does not contain the Irish extension because the description `355218015` is marked as preferred in the GB language reference set but the Irish language reference set is not present. Perhaps you imported the Irish extension on another branch (this would be in line with best practice). You may have imported the Irish extension onto a branch like `MAIN/SNOMEDCT-IE` as we have in the public Snowstorm instance. In that case you would need to use that branch to access the Irish content. 

For example viewing the concept: (/browser/MAIN/SNOMEDCT-IE/concepts/236990004)[https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-IE/concepts/236990004] .. here you can see that the description `355218015` has this acceptability map:
```
"acceptabilityMap": {
"900000000000508004": "PREFERRED",
"21000220103": "PREFERRED"
}
```
This contains both the  `900000000000508004 | Great Britain English language reference set (foundation metadata concept) |` and `21000220103 | Irish language reference set (foundation metadata concept) |`.

Because this branch contains the Irish extension we can request the Irish preferred terms to be returned from the API.. for example: 
```
$ curl -H 'Accept-Language: en-X-21000220103,en-X-900000000000509007' https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/SNOMEDCT-IE/concepts/236990004
{
  "conceptId" : "236990004",
  "active" : true,
  "definitionStatus" : "PRIMITIVE",
  "moduleId" : "900000000000207008",
  "effectiveTime" : "20020131",
  "fsn" : {
    "term" : "Postmortem cesarean section (procedure)",
    "lang" : "en"
  },
  "pt" : {
    "term" : "Postmortem caesarean section",
    "lang" : "en"
  },
  "id" : "236990004"
}
```

I would recommend using a separate code system with its own branch like this when loading extensions into Snowstorm.

**Comment by kandascan** [comment]
Hi Kai,

I created new code systems for this branch: MAIN/SNOMEDCT-IE

here is respons from API to see if it was created successfully:
`http://localhost:8080/codesystems?forBranch=MAIN%2FSNOMEDCT-IE`
`{
  "items": [
    {
      "shortName": "SNOMEDCT-IE",
      "branchPath": "MAIN/SNOMEDCT-IE",
      "dependantVersionEffectiveTime": 20210131,
      "dailyBuildAvailable": false,
      "languages": {
        "en": "English"
      },
      "modules": [
        {
          "conceptId": "900000000000012004",
          "active": true,
          "definitionStatus": "PRIMITIVE",
          "moduleId": "900000000000012004",
          "effectiveTime": "20020131",
          "fsn": {
            "term": "SNOMED CT model component module (core metadata concept)",
            "lang": "en"
          },
          "pt": {
            "term": "SNOMED CT model component",
            "lang": "en"
          },
          "id": "900000000000012004"
        },
        {
          "conceptId": "449080006",
          "active": true,
          "definitionStatus": "PRIMITIVE",
          "moduleId": "900000000000012004",
          "effectiveTime": "20110731",
          "fsn": {
            "term": "SNOMED CT to ICD-10 rule-based mapping module (core metadata concept)",
            "lang": "en"
          },
          "pt": {
            "term": "SNOMED CT to ICD-10 rule-based mapping module",
            "lang": "en"
          },
          "id": "449080006"
        },
        {
          "conceptId": "900000000000207008",
          "active": true,
          "definitionStatus": "PRIMITIVE",
          "moduleId": "900000000000012004",
          "effectiveTime": "20020131",
          "fsn": {
            "term": "SNOMED CT core module (core metadata concept)",
            "lang": "en"
          },
          "pt": {
            "term": "SNOMED CT core",
            "lang": "en"
          },
          "id": "900000000000207008"
        }
      ]
    }
  ],
  "total": 1,
  "limit": 1,
  "offset": 0
}`
then I created new import job and loaded file:
![image](https://user-images.githubusercontent.com/15519926/111647752-0845be80-8803-11eb-8056-689c4e6c9ff8.png)
I checked loading progress:
`http://localhost:8080/imports/185709bf-70f7-4ab2-9189-919c07617661`
`{
  "status": "COMPLETED",
  "branchPath": "MAIN/SNOMEDCT-IE",
  "createCodeSystemVersion": true,
  "moduleIds": [],
  "type": "SNAPSHOT"
}`
it seems all is find so far, so I try to do curl requst like on your example:
![image](https://user-images.githubusercontent.com/15519926/111649489-b56d0680-8804-11eb-9776-ce43b94acd75.png)
It seems now I got the results I needed.

I appreciate your help Kai

**Comment by kaicode** [comment]
You are welcome. I'm glad it's working for you now 👍
