### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by nicoavila** [IHTSDO/snowstorm#25]
Hi Everyone
Is there a way to enable/configure CORS in the server?
Thanks!

**Comment by kaicode** [comment]
Hi @nicoavila, Snowstorm is a Spring Boot application. There are a few options to enable CORS support in code - https://www.baeldung.com/spring-cors
However if we were to add CORS support in Snowstorm we should be able to configure it from the application.properties file rather than having to rebuild the application because not everyone will want it on. For this reason it's not straightforward to add.
SNOMED International currently use [NGinx](https://nginx.org/en/) in front of all Java applications which it an ideal place to add required HTTP headers like CORS support.

**Comment by nicoavila** [comment]
Thank you for your advice @kaicode 😄!

**Comment by StephanMeijer** [comment]
+1 for built-in support
