### ISSUE TITLE
[Error 500] Code from main branch not found on extension branch

### ISSUE THREAD

**Issue by Lotili** [IHTSDO/snowstorm#251]
Hi !

After the 2021-01-31 international release we realized that some new codes hadn't been inherited by extension branches (under MAIN). It seems like it concerns only brand new codes that were created at the 2021-01-31 release (so not codes that have been inactivated then reactivated in January). 

Here are 2 examples that we tested : `1003721002` and `969688801000119108`. Both codes respond with an error 500 `INTERNAL_SERVER_ERROR` with routes `GET /browser/{branch}/concepts` and `GET /{branch}/concepts` on branch MAIN/SNOMED-BE. However, we have no such error with the MAIN branch. We update our Snomed versions with the "DELTA" tag.

Our questions:
1. What can be the source of this issue? Maybe an import problem? If so, how can we fix it without scratching it all
2. Is an Error 500 expected when a code is not found? 

Thanks in advance for any enlightenment you can provide :)
Lotili

**Comment by kaicode** [comment]
Hi @Lotili,

We expect a 404 (not found) response when a concept is not found or a 400 (bad request) response when the branch is not found so you are right to be concerned about the 500 error.
For example: https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/concepts/123123
(Error responses is in XML format rather than JSON which is inconsistent with the rest of the API. I would like to fix this but I'm a little weary about breaking existing implementations.)

**The procedure for upgrading an extension**
- Wait until there is a new Extension release (in your example it looks like this would be the Belgian 2021-03-15 release)
- Upgrade the International branch MAIN by importing the 2021-01-31 International Edition RF2 using DELTA
- Upgrade the Extension code system:
  - use the `POST /codesystems/{shortName}/upgrade` function with the request: `{ "contentAutomations": false, "newDependantVersion": 20210131 }`
  - then import the new Extension release on the code system branch using DELTA

**Checking that the upgrade was successful**
After a successful Extension upgrade to the Jan 2021 International Edition the code system should say `"dependantVersionEffectiveTime": 20210131`, for example: 
<img width="683" alt="Screenshot 2021-04-06 at 09 59 52" src="https://user-images.githubusercontent.com/2010517/113686166-e0899e00-96be-11eb-8909-1d685cc0ae47.png">

There should also be a new Extension code system version:
<img width="753" alt="Screenshot 2021-04-06 at 10 02 00" src="https://user-images.githubusercontent.com/2010517/113686426-28a8c080-96bf-11eb-931e-8dc783b3d163.png">

And a final check could be that the Jan 2021 description is shown on the root SNOMED CT concept (138875005) using the new extension release branch:
<img width="943" alt="Screenshot 2021-04-06 at 10 06 30" src="https://user-images.githubusercontent.com/2010517/113687066-d916c480-96bf-11eb-9877-237e14ffbc39.png">

If all of these checks pass and you still have the 500 error then please capture the error stack trace from the Snowstorm logs and share that to help us debug the issue.

I hope that helps!

**Comment by Lotili** [comment]
Hi Kai !

Thank you for this clear and detailed answer!

Indeed we missed one step : upgrading the extension code system's "dependent version". Actually we never did this step and the dependent version was the 2020-01-31 release, which explains a lot. 
Since I had already made the 2021-03-15 import of the Belgian release I just upgraded the code system. I performed the checks you recommended, everything seems fine on the code system data. The last check, however, is only validated if I query on branch `MAIN/SNOMED-BE`, not `MAIN/SNOMED-BE/2021-03-15`. I'm guessing it's because I imported it before upgrading the code system. I also still have the error 500 on branch `MAIN/SNOMED-BE/2021-03-15` when trying `GET /browser/MAIN/SNOMED-BE/2021-03-15/concepts` with code `1003721002`. 
That said, we use `MAIN/SNOMED-BE` so this works fine for us. And I'm guessing it will sort itself out if we follow the right steps for the next release extension.

I could still provide the log capture if needed.

Thanks again !
Lotili

**Comment by kaicode** [comment]
Hey. 
It's up to you if you would like to unpick the commits made on the `MAIN/SNOMED-BE` branch to resolve the issue in the release branch. There is an admin commit-rollback function available if you would like to revert the upgrade, code system version and delta import then run through those again.
You are right that the `MAIN/SNOMED-BE` branch should be fine and the release branch for the next release in six months should be unaffected.

I'm glad you got it sorted.

Kind regards,
Kai Kewley
