### ISSUE TITLE
Importing translations

### ISSUE THREAD

**Issue by ruscoder** [IHTSDO/snowstorm#274]
Hi! I'm trying to import translation file I've downloaded from https://refset.ihtsdotools.org/#/directory for French. The archive includes two files: 
- sct2_Description_Snapshot-fr_MAIN_2020-01-31
- der2_cRefset_LanguageSnapshot-fr_MAIN_2020-01-31
When I'm trying to import this archive using snowstorm's import endpoint, I got the error in logs that concept and relationship files are missing.

Is there a proper way to import translations?

**Comment by kaicode** [comment]
Hi @ruscoder, yes, Snowstorm needs a few more files in order to recognise the RF2 archive. These will just contain the header line. This check prevents files being missed from the import because of typos in the naming.

Here is an empty RF2 snapshot archive which has the files required to import into Snowstorm. The dates in the filenames are not used, so leaving them as they are is fine.
[empty-snomed-rf2-snapshot.zip](https://github.com/IHTSDO/snowstorm/files/6591157/empty-snapshot.zip)

If you add your files to the archive then it will import as expected.

Kind regards,
Kai Kewley

**Comment by ruscoder** [comment]
Thanks for the response @kaicode!
I've successfully imported the translation. And I see french terms using `https://server/browser/MAIN/concepts?conceptIds=774604001` with `accept-language: fr` header.
```
{
  "items": [
    {
      "conceptId": "774604001",
      "fsn": {
        "term": "Product containing only anagrelide (medicinal product)",
        "lang": "en"
      },
      "pt": {
        "term": "médicament contenant seulement anagrélide",
        "lang": "fr"
      },
```

But using FHIR endpoint, it shows empty display.
```curl 'https://server/fhir/ValueSet/$expand?displayLanguage=fr&url=http://snomed.info/sct?fhir_vs=ecl/774604001' ```
with `accept-language: fr` header:
```
{"resourceType":"ValueSet","url":"http://snomed.info/sct?fhir_vs=ecl/774604001","expansion":{"total":1,"offset":0,"contains":[{"system":"http://snomed.info/sct","code":"774604001"}]}}
```

Maybe something else is required to do?

**Comment by ruscoder** [comment]
In logs I see: 
```
2021-06-03 12:01:52.299  INFO 1 --- [nio-8080-exec-9] o.s.s.f.services.FHIRValueSetProvider    : Recovered: 1 concepts from branch: MAIN/2021-01-31 with ecl: '774604001'
```

But I imported translation into the MAIN branch and the international version Is also imported into the MAIN. Is there a way to specify branch for $expand operation?

**Comment by ruscoder** [comment]
I found the way of specifying the particular version, e.g. `https://server/fhir/ValueSet/$expand?url=http://snomed.info/sct/900000000000207008/version/20200202?fhir_vs=ecl/774604001`.

And then it goes to the French version branch `Recovered: 1 concepts from branch: MAIN/2020-02-02 with ecl: '774604001'`.

But is it possible to use the actual MAIN branch?

**Comment by kaicode** [comment]
The `MAIN` branch is usually a working branch and can contain unpublished content. Content on `MAIN` can be accessed via the FHIR interface using the `http://snomed.info/xsct` code system url. 

For example the concept `1162411006 |Aloe vera|` has not been published yet so it's not accessible via using the standard url:
https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/1162411006
(This link will probably start working on July 31 2021)

But it can be accessed using the xsct url:
https://snowstorm.ihtsdotools.org/fhir/ValueSet/$expand?url=http://snomed.info/xsct?fhir_vs=ecl/1162411006

**Comment by ruscoder** [comment]
@kaicode Thanks!
Are there best practices for organizing a multi-language terminology server without using the MAIN branch directly?
It's quite difficult to have translation extensions for all needed languages with the same version as the edition's version. So it leads to the problem I have.

Is it possible to have this behavior: for example, I have the latest version of the international edition and not the latest version of the French translation. If there is no translation for the concept in the latest version, it should be found in one of the previous.

**Comment by ruscoder** [comment]
It seems, I just needed to merge the MAIN branch to the latest one after importing new translation extensions. Is this a proper solution?

**Comment by kaicode** [comment]
It's an interesting idea to have all translations imported onto a single branch. In theory as long as these translations only contain descriptions, language refset members and metadata concepts this should work. If any of the extensions contain medical concepts they should probably be kept in separate branches so that it's clear they are not part of the International Edition.

We usually recommend creating a separate Code System entry for each Extension and importing them into a branch for that Code System. For example the Canadian Extension would have a Code System named SNOMECT-CA, the content would live on the branch MAIN/SNOMECT-CA.

This allows for clear separation between content and management of upgrades. Each Code System can be upgraded onto the dependant International version before importing the new release content. See [Loading & updating SNOMED CT with local Extensions or Editions](https://github.com/IHTSDO/snowstorm/blob/master/docs/updating-snomed-and-extensions.md).

Snowstorm has a multisearch function which allows searching across the release branches of all extensions: 
[GET /multisearch/descriptions](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/swagger-ui.html#!/MultiSearch/findDescriptionsUsingGET_1)

Otherwise another approach would be for your application to select the most relevant branch based on the language requested.
