### ISSUE TITLE
Error Uploading SNOMED

### ISSUE THREAD

**Issue by dominik160** [IHTSDO/snowstorm#317]
Hey, 
I am in the process of loading SNOMED into Snowstorm. As described in the instructions, I create a new FULL import job and start the upload of the RF2 file of the international version of July 2020. I have already tried to upload the complete ZIP and to unzip the ZIP and to zip and upload only the FULL folder. Both times I get an error after about an hour. What am I doing wrong?
Thanks a lot
[snowstorm_error.txt](https://github.com/IHTSDO/snowstorm/files/7141732/snowstorm_error.txt)

**Comment by kaicode** [comment]
Hi!
Thank you for providing your log output. 

The warning messages from `o.e.m.j.JvmGcMonitorService` show that gargage collection within Elasticsearch starts to take longer than 30 seconds at `2021-09-09T21:52:06,442Z`. This causes one of the calls from Snowstorm to Elasticsearch to time out.

It looks like you might have assigned a maximum of 4g of heap space to Elasticsearch? Check that you have also set the minimum heap space to the same size as the maximum. Although ideally Elasticsearch would only use the memory as it's required, if you give the same minimum and maximum then the performance should be better because the garbage collector will not kick in so much.

Other things to try:
- Import the SNAPSHOT if you only need access to the latest release. The FULL takes much longer to import and will require more than 4g to import.
- Try increasing the memory given to Elasticsearch during the initial import and then set it back to something lower when ready to serve the imported content.

I hope that helps!
Kai

**Comment by dominik160** [comment]
Hi! 
Thank you for the quick answer. Unfortunately, the error is also thrown when uploading the snapshot. Do I see it correctly that the minimum and maximum heap can be set in the docker compose file via "ES_JAVA_OPTS = -Xms4g -Xmx4g" at the elasticsearch service? I've already tried to use 5g space here. This also throw the error just a little bit later.Is the solution now going up with the space until it works or is there a other solution?

Thanks :) 
[snapshot-log.txt](https://github.com/IHTSDO/snowstorm/files/7144246/snapshot-log.txt)

**Comment by kaicode** [comment]
In your snapshot log I can see 5g, in the Elasticsearch GC monitor output, so that must be working.

It looks like Elasticsearch is still not running fast enough to avoid the 30 second timeout. Memory is not the only thing that can make Elasticsearch slow. It's possible that your setup is not fast enough to allow the import to complete. Perhaps there is insufficient CPU or disk speed. 

Consider running the import in a higher spec environment. You have the option of backing up the Elasticsearch indices from one environment and restoring them in a lower spec environment after the import if necessary. If using a cloud instance you may be able to scale up the resources just for the initial import.

**Comment by dominik160** [comment]
Thanks a lot! On a other system it works.
