### ISSUE TITLE
Creating new concepts and descriptions in local extension

### ISSUE THREAD

**Issue by Lotili** [IHTSDO/snowstorm#32]
Hi,

We are currently testing the creation of a local extension with Snowstorm. Ideally, we would like to create the whole basis with the tools provided by Snowstorm.

I tried to create the first module concept and its descriptions and relations. Apparently it worked, but the created concept has the following key-value : ``"released" : false`` , no matter the effectiveTime (or releasedEffectiveTime, for relations) provided. When I search for the concept with `` get/{branch}/concepts ``, here is the response:
```
{
  "items": [],
  "total": 1,
  "limit": 50,
  "offset": 0
}
``` 
Which, I'm guessing, means that the concept exists, but can't be extracted because it was not released.
Any insight as to why ``"released" `` is ``false`` and how to solve this?

Note: we do not have RF2 files to import for our extension as the whole test is about starting a new extension from scratch with Snowstorm.

**Comment by kaicode** [comment]
Hi @Lotili,

Thanks for getting in touch. I must warn you that although Snowstorm has been tested for hosting published SNOMED CT Extensions it has not yet been tested for creating and maintaining Extensions. 

## Identifiers
The immediate problem will be generating identifiers for your components. We use an external service for this called [CIS](https://github.com/IHTSDO/component-identifier-service) which is capable of generating unique SCTID identifiers with the correct [extension namespace and segment](https://confluence.ihtsdotools.org/display/DOCRELFMT/6.2+SCTID+Representation). The identifiers CIS generates are sequential which is not strictly required but preferred by some. This is the only current implementation of the _IdentifierSource_ class within Snowstorm but you could always create your own depending on your requirements.

## Code Systems
For authoring an extension I would recommend using the Code Systems within Snowstorm.
Start by importing an International Edition release snapshot (see [loading SNOMED CT](docs/loading-snomed.md)). 
This will create the international code system **SNOMEDCT** listed under *GET /codesystems*

Next you should create a code system for your own extension. You can do this in the Swagger API page under *POST /codesystems*. For example: `{
  "branchPath": "MAIN/SNOMEDCT-LOTILI",
  "shortName": "SNOMEDCT-LOTILI"
}`
This will create the **MAIN/SNOMEDCT-LOTILI** branch. You should do all of your authoring work on this branch. The new content will have a released flag of false until your authoring is complete and you are ready to do the first release of your extension. Concepts you create will be accessible straight away on this branch. The release flag on the content will be set to false but that's okay during the authoring cycle (period of time where you are creating the release content).

When you are ready to release your content use the REST API to create a new version of your extension code system using *POST /codesystems/{shortName}/versions*. For example: *shortName: SNOMEDCT-LOTILI, input: `{
  "description": "April 2019 Release",
  "effectiveDate": 20190401
}`*
This will give all your authored content an effectiveTime of 20190401 and set the release flag to true. It will also create a release branch *MAIN/SNOMEDCT-LOTILI/2019-04-01* which will contain all your released content.

You can then start authoring for your next release on *MAIN/SNOMEDCT-LOTILI* and still see the version of your extension from your last release.

We use the SNOMED Release Service and Release Validation Framework to test the content and package the final release. Snowstorm can export the RF2 files for your extension in DELTA or SNAPSHOT format but there is no FULL export implemented because we rely on the release services to produce the final release package.

## Final Notes
This is a brief outline of the process. As I said authoring of extensions has not been tested although SNOMED International does plan to complete and test this work during the last quarter of 2019.

As will all open source software we offer no guarantee. Please complete your own testing to satisfy yourselves that this will work for you.

Kind regards,
Kai Kewley

**Comment by Lotili** [comment]
Thank you for your detailed answer !
I think the provided services are enough for a beginning, but I could come back to you if we encounter further issues during our tests. 
I'm closing the issue :)

**Comment by kaicode** [comment]
Great, thanks @Lotili. I hope it goes well.

**Comment by kaicode** [comment]
Update: In the last year we have moved all our managed service customers to Snowstorm and are successfully maintaining 14 different codesystems in production, the International Edition plus 13 extensions.

Please see the documentation on setting up Snowstorm for [extension authoring](https://github.com/IHTSDO/snowstorm/blob/master/docs/extension-authoring.md).

@Lotili I've added an Identifier Generation section to the doc above to answer your questions in this area.
