### ISSUE TITLE
Result Limitation Concept Search

### ISSUE THREAD

**Issue by alexandragrau** [IHTSDO/snowstorm#337]
Hello! (I am sorry if this question might be duplicated, I am a little new to this) 

My matter: I want to retrieve a list of all concepts under concept "404684003" with display name and code.

When I use the public API https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=isa/404684003 it is limited to 1,000 entries and I cannot retrieve the expected 114,784 entries.

How can I retrieve all display/code information for all 114,784 entries? Would a local snowstorm service give me the unlimited results or is that one also limited?

Thanks for the help!
Alexandra

**Comment by pgwilliams** [comment]
Hi Alexandra.   See the API spec here:  http://build.fhir.org/valueset-operation-expand.html   the parameters you need are offset and count, and bear in mind that the offset is the number of records to skip, not the number of pages as you might expect.    To make everyone's life simple, we've said that your offset has to be an integer multiple of your page size.   So you're effectively requesting page N at any point, we don't allow starting half way through a page.

So you can get the next 1000 concepts with https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=isa/404684003&offset=1000&count=1000

The other limit we've historically hit is at 10,000 because the ElasticSearch database needs to use a technique called 'SearchAfter' to break this limit, but we shield the user from having to know that, so let me just check that's working as expected...    https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=isa/404684003&offset=10000&count=1000     yes looks good.

And then your final page should only contain 784 concepts...    https://snowstorm-fhir.snomedtools.org/fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=isa/404684003&offset=114000&count=1000

Checking...
pbpaste | grep display | wc -l
784

Exactly right!

**Comment by alexandragrau** [comment]
Hi Peter, thank you for the really fast and detailed answer. It helped a lot - have a great day!
