### ISSUE TITLE
Problem with ElasticSearch ( TOO_MANY_REQUESTS )

### ISSUE THREAD

**Issue by killianRo** [IHTSDO/snowstorm#409]
Hello, I have some issue when I use elasticSearch and snowstorm. I don't know why, but I have the following error:

ElasticsearchException.getFailedDocuments() for detailed messages [{global-ADMIN=ElasticsearchException[Elasticsearch exception [type=cluster_block_exception, reason=index [admin-permission] blocked by: [TOO_MANY_REQUESTS/12/index read-only / allow delete (api)];]]}].

I also have a problem with the flood stage which exceeds 95 % whereas I still have space in my disk. 

Kind regards,

**Comment by kaicode** [comment]
Hi @killianRo. The last part of the message `read-only / allow delete` shows that the indices are locked. This is usually triggered by lack of disk space. 

In order to get Elasticsearch running again: 
- First
  - Either free up disk space on the machine
  - Or change the [disk watermark settings](https://www.elastic.co/guide/en/elasticsearch/reference/7.17/modules-cluster.html#disk-based-shard-allocation) by editing/adding lines to the `elasticsearch/config/elasticsearch.yml` config file and restarting Elasticsearch
- Then unlock the indices:
```
curl -X PUT "localhost:9200/*/_settings?pretty" -H 'Content-Type: application/json' -d' { "index.blocks.read_only_allow_delete": null }'
```

Snowstorm should then be restarted.

I hope that helps!
