### ISSUE TITLE
Merge conflict cannot be saved after DailyBuild rollback/import

### ISSUE THREAD

**Issue by hurtigcodes** [IHTSDO/snowstorm#410]
Hi,
We have an incident in which a merge conflict is stopping a rebase to a child branch under our codesystem path: `MAIN/SNOMEDCT-NO` => `MAIN/SNOMEDCT-NO/REFSETS` 

We have two versions of a metadata concept on the two different branches. I  deleted the concept entirely from the child branch and re-run the merge review and it reports that there's a conflict still.

To add, I have also tried to save the version from the parent branch using the `POST /merge-reviews/{id}/{conceptId}` endpoint and applied the merge-review successfully. Everything works smoothly at that point. However, when the DB is rolled back and imported again the same problem comes back. Why is this?  

When querying Elasticsearch I'm seeing multiple documents which represent this concept:
```
{
  "_index" : "concept",
  "_type" : "_doc",
  "_id" : "LYerHoEBZHoT-xaHz5z1",
  "_score" : 5.676825,
  "_source" : {
    "_class" : "org.snomed.snowstorm.core.data.domain.Concept",
    "conceptId" : "187571000202107",
    "definitionStatusId" : "900000000000074008",
    "active" : true,
    "moduleId" : "51000202101",
    "released" : false,
    "internalId" : "LYerHoEBZHoT-xaHz5z1",
    "path" : "MAIN/SNOMEDCT-NO/REFSETS",
    "start" : 1654076983870,
    "end" : 1654192156125
  }
```

My hypothesis is that even though Snowstorm cannot find the concept on the `/concepts` endpoint the concept is still there in Elastic, which could be why the `/merge-review` endpoint cannot execute.

**Comment by hurtigcodes** [comment]
Hey @kaicode, this is an issue in reference to the discussion we had. Reiterating but saving the correct version didn't suffice as the same problems comes back after rollback.

**Comment by kaicode** [comment]
The Snowstorm version control system works on a timeline per branch. Component documents are not usually deleted from the store, instead they are ended using a datestamp in the `end` field or if they exist in an ancestor branch they are hidden using the branch versionsReplaced collections. This explains why those concept documents could be found in Elasticsearch after the concept was deleted.

The Snowstorm DailyBuild (import and rollback) functionality is designed to mirror content from an authoring platform into a read-only browser type platform. In general rolling back commits is only safe if there are no child branches using those commits, otherwise we should expect unpredictable behaviour in the child branches.

I'm not sure what would happen if the concept document is removed from all commits on the timeline. If that approach was to work I think the corresponding language reference set, description, axiom and relationship documents should also be removed.

@hurtigcodes If you are still stuck with this later today feel free to reach out to me. We could have a call to analyse this.

**Comment by hurtigcodes** [comment]
Hi @kaicode, thank you that makes sense. So, if I want to restore a hidden document I could use `ctx._source.remove(\"end\")"`? 

In any case... and for any person with this problem in the future: 
We decided to instead hard-delete the branch and start fresh from a backup. Earlier, I set up a nightly configurable export saved to an RF2 archive, which also helps us easily sync and port data between servers. Check the refset.types section in application.properties.
