### ISSUE TITLE
Merging Branches

### ISSUE THREAD

**Issue by steve1973** [IHTSDO/snowstorm#415]
Hi there

I used to be able to import the UK Drug Dictionary on to it's own branch, but this has been failing with a Java Null Exception after processing for a time. I can however import it on to the MAIN/SNOMEDCT-UKC branch. It appears I have to then run a merge from MAIN/SNOMEDCT-UKC into MAIN/SNOMEDCT-UKC/2022-05-11. How do I do this through the Swagger Interface please?

Many thanks

**Comment by kaicode** [comment]
Hi @steve1973, feel free to send the stack trace from the null pointer exception if you would like us to try to diagnose that.

Additional content can be imported into code system branch, and the release branch rebased, if there is no daily build or other content imported since importing the release.

The release branch can be rebased using `POST /merges` using request body:
```
{
  "source": "MAIN/SNOMEDCT-UKC",
  "target": "MAIN/SNOMEDCT-UKC/2022-05-11"
}
```

**Comment by steve1973** [comment]
Thanks @kaicode, I think this method works for us, but if I need to go back to importing on a separate branch I'll report back with the error if it's still occurring.

**Comment by kaicode** [comment]
Okay, thanks.
