### ISSUE TITLE
Classifications

### ISSUE THREAD

**Issue by igerne94** [IHTSDO/snowstorm#474]
We're working on a project where we need to classify a couple of concepts authored with Snowstorm. We found this documentation very useful: https://github.com/IHTSDO/snowstorm/blob/master/docs/extension-authoring.md

We have one question though: When using the POST /{branch}/classifications endpoint, an endpoint (/classifications) in the Classification service seems to be called. Should we just install the Classification service on the same environment? Do we need any additional configuration, or would this trigger a proper classification on the branch - and write back classified (inferred) concept back to Snowstorm?

Hanna, developer Conteir Noway

**Comment by kaicode** [comment]
Hi Hanna,

Snowstorm delegates the classification function to an external service to allow that memory and CPU intensive service to be load balanced or autoscaled between many [Classification Service](https://github.com/IHTSDO/classification-service) instances.

The Classification Service needs 3 or 4g to classify most editions. You can host that wherever you have enough memory.
Snowstorm configuration options for communicating with the Classification Service can be found [here](https://github.com/IHTSDO/snowstorm/blob/7.12.0/src/main/resources/application.properties#L325). 

In order to use the classification function from the Snowstorm API:
- Make sure `dependencyPackage` and `previousPackage` are set in the branch metadata of the code system being authored
- Make sure the packages named in the metadata are available in the store/releases directory under the classification service (this can be changed to an AWS S3 bucket location, see classification service config)
- Create a classification job in Snowstorm
  - The API returns a Location header containing the URL of the new classification job
  - The authoring changes will be exported in an RF2 delta and sent to the classification service
- Monitor the classification job via the Snowstorm API until the status is complete
- The classification results (inferred relationship changes) are not applied to the branch straight away. This gives authors a chance to review the classification results before accepting or discarding them.
- Preview the classification results using the classification job detail endpoints `/relationship-changes`, `/equivalent-concepts` and `/concept-preview/{conceptId}`
- To accept the classification results and apply the inferred relationship changes to the branch use `PUT /{branch}/classifications/{classificationId}` with a payload `{ "status": "SAVED" }`.
- Once the changes we should expect that running classification again results in no new changes.

After versioning the extension, by creating a new Code System version `POST
/codesystems/{shortName}/versions`, then the `previousPackage` metadata item must be updated with the new RF2 snapshot.
After upgrading the extension to a dependant release, using `POST
/codesystems/{shortName}/upgrade`, then the `dependencyPackage` metadata item must be updated.
If these are not kept up to date classification will be run with the wrong packages.

**N.B.** `dependencyPackage` is only required if `previousPackage` is an extension package, meaning that it does not contain the concepts from the International Edition. If `previousPackage` is an edition package, like the US edition, then the `dependencyPackage` is not required for classification.

I hope that gets you started in the right direction. Just shout if you have more questions.

Kai

**Comment by igerne94** [comment]
Do I need to install the [Snomed OWL Toolkit](https://github.com/IHTSDO/snomed-owl-toolkit) before this installation?

**Comment by kaicode** [comment]
No need to install the toolkit. The SNOMED OWL Toolkit is built into the Classification Service. The service is like a REST API wrapper for the toolkit.

**Comment by eirikconteir** [comment]
I have a question as well:) Would the classification service work when building an extension upon an extension - in this case the Norwegian extension? If so, I'm not sure which dependency package to use? It certainly needs both the international edition and the extension to classify correctly?

**Comment by igerne94** [comment]
More questions came
I added the .jar file on the VM. I can run .jar and explore endpoints.
I was trying to connect the classification service to our snowstorm service through the snowstorm.service config. But about this statement: classification-service.url=http://our-classification-service:8089/classification-service the snowstorm service returns _"Unknown key name 'classification-service.url' in section 'Service', ignoring."_. And the same about the others I have added.
Where to find the store/releases directory? It is not in the folder where I have .jar.
How it's possible to run the classification service automatically without starting .jar every time?

**Comment by kaicode** [comment]
@eirikconteir 
> I have a question as well:) Would the classification service work when building an extension upon an extension - in this case the Norwegian extension? If so, I'm not sure which dependency package to use? It certainly needs both the international edition and the extension to classify correctly?

The Classification Service is not currently able to take more than one dependency package. I agree that if you are creating an extension on top of the Norwegian extension then the International Edition should also be used as a second dependency package (because the national extension package is not an "edition" package so doesn't contain the international content). The SNOMED OWL Toolkit, that does the work, is capable of using multiple dependency packages so this is just a REST interface issue.

We don't want to make any breaking changes to the REST API if we can help it but making the dependencyPackage parameter into a list (or allowing the parameter to be used more than once) should be a backwards compatible change. Then I would expect your extension on an extension on an edition to classify correctly :)

If you [raise an issue against the Classification Service](https://github.com/IHTSDO/classification-service/issues/new) I will see what I can do to fix this.

**Comment by kaicode** [comment]
@igerne94 

This is a high level layout of the directories and files you need.
- snowstorm/
  - snowstorm.jar
  - application.properties
- classification-service/
  - classification-service.jar
  - application.properties
  - store/
    - releases/
      - SnomedCT_InternationalRF2_PRODUCTION_20230131T120000Z.zip

It doesn't matter where these snowstorm and classification-service directories live. The jar files may have slightly different names. The release file I have given is just an example and you may need more than one of these.

The application.properties in the snowstorm directory should contain a line like:
```
classification-service.url=http://our-classification-service:8089/classification-service
```
A line is only needed in your application.properties for configuration items that you would like to change. The rest will be taken from the [default configuration](https://github.com/IHTSDO/snowstorm/blob/7.12.0/src/main/resources/application.properties) which already built into the application.

The application.properties file in the classification-service directory may not be needed. You could not create it or make a blank file for later.

Most people run the jar files from the command line. You should change to the snowstorm directory before starting the jar. Similarly, in a second command line, you should change to the classification-service directory before starting that jar. This way the applications will be able to find their own configuration files and other resources.

The Classification Service must be running to work. Snowstorm can not start that for you.

If you intend to use Snowstorm and the Classification Service it may be worth having a startup script that you can use to launch them with the correct memory parameters (e.g. `-Xms4g`) without typing out command each time. Let me know if I can help with that. I have not included an example because it depends on your operating system.

**Comment by eirikconteir** [comment]
> @eirikconteir
> 
> > I have a question as well:) Would the classification service work when building an extension upon an extension - in this case the Norwegian extension? If so, I'm not sure which dependency package to use? It certainly needs both the international edition and the extension to classify correctly?
> 
> The Classification Service is not currently able to take more than one dependency package. I agree that if you are creating an extension on top of the Norwegian extension then the International Edition should also be used as a second dependency package (because the national extension package is not an "edition" package so doesn't contain the international content). The SNOMED OWL Toolkit, that does the work, is capable of using multiple dependency packages so this is just a REST interface issue.
> 
> We don't want to make any breaking changes to the REST API if we can help it but making the dependencyPackage parameter into a list (or allowing the parameter to be used more than once) should be a backwards compatible change. Then I would expect your extension on an extension on an edition to classify correctly :)
> 
> If you [raise an issue against the Classification Service](https://github.com/IHTSDO/classification-service/issues/new) I will see what I can do to fix this.

Thank you so much, Kai! I (we) really appreciate your priceless guidance here.

I currently work with/for the Norwegian NRC. From time to time the possibility to create separate extensions built upon the Norwegian edition is on the table, mostly as a theoretical issue raised by other governmental bodies and vendors. It's great to read it probably would be possible from a tech/tooling perspective.

When it comes to the use-case which has triggered this issue, I believe it's about creating a pilot for patient friendly terms and definitions (inspired by the Dutch edition). I think there is only a couple of metadata concepts which has to be classified. And those concepts have a stated as-is relationship to concepts from the Norwegian edition. If so, it would be no biggie to run the classification based on the International edition, and manipulate the result manually afterward. It's a hack, but it will do the job:)

Anyhow; I'll ask the project owner to raise an issue Monday. 

Thank you so much, and enjoy your weekend:)
