### ISSUE TITLE
nursing procedure record

### ISSUE THREAD

**Issue by juanidepapi** [IHTSDO/snowstorm#490]
hi guys

How can I make an ecl query that brings me only nursing procedures.
The idea is that the doctor indicates the nursing process in the HCE, for example "injection application" or "wound healing"

thank you so much!

**Comment by juanidepapi** [comment]
I have made the following ecl query:
<<71388002
with the term "wound healing", but I didn't get any terms that came close to the idea.
I'm using the Argentine edition.

**Comment by kaicode** [comment]
Hi @juanidepapi, it can be hard to define an area of SNOMED CT for nursing because nursing often covers a wide range of care activities.

There are some existing sets of nursing related content in the International Edition, for example:
- 1157358007 |International Classification for Nursing Practice reference set|
- 733990004 |Nursing Activities Reference Set|
- 733991000 |Nursing Health Issues Reference Set|
These could be included in an ECL query if it helps. For example to search for procedures within the "International Classification for Nursing Practice reference set" we can use the ECL: `<< 71388002 |Procedure| AND ^1157358007 |International Classification for Nursing Practice reference set|`.

The ECL `<<71388002` that searches all procedures looks fine. I get 5 results when searching the [Argentine edition in the SNOMED International browser](https://browser.ihtsdotools.org/?perspective=full&conceptId1=404684003&edition=MAIN/SNOMEDCT-ES/SNOMEDCT-AR/2022-11-30&release=&languages=es,en), as long as I do **not** select the "América Latina" language refset. If that is selected then the search term must be Spanish.
<img width="662" alt="Screenshot 2023-03-02 at 15 12 09" src="https://user-images.githubusercontent.com/2010517/222469165-382e0550-c895-4143-9957-337846396c5d.png">

There is no fuzzy matching in the browser (which uses the Snowstorm terminology server). The search strategy uses multiple prefix, any order matching. So for example a search term of "wou hea" would match the concept `Education about wound healing`.

If this is still not working for you please let me know if you are using this or another browser / API so I can suggest something else.

**Comment by kaicode** [comment]
With the two examples you gave it may be helpful to start an ECL that includes a concept closer to what you are looking for, before refining further using text.
For example: 
- `<59108006 |Injection (procedure)|` .. then a text search of the body site or substance.
- `< 225365006 |Care regime (regime/therapy)|` .. then a text search of "wound".

**Comment by juanidepapi** [comment]
hello kai.
thanks for your answer.
Understand what you say.
I was wondering if there isn't a mapping from NIC (Nursing interventions classification) to Snomed to be more specific in terms of nursing terminology.
While I investigate this I will apply what you say.
A greeting and thank you very much again
