### ISSUE TITLE
Loinc 2.74

### ISSUE THREAD

**Issue by rajayeswanth** [IHTSDO/snowstorm#500]
when will get support for Loinc versions greater than 2.72 @kaicode

**Comment by kaicode** [comment]
Thank you for your question. There was a file path change within the newer Loinc packages, 2.73 and later, that the package loader doesn't yet recognise. We will aim to get this fixed in the next one or two releases of Snowstorm.

I just tested a workaround, that involved changing the path of the `ComponentHierarchyBySystem.csv` file within newer packages, however the import did not complete successfully for a different reason. Snowstorm currently expands each Loinc value set during import in an attempt to validate quality but I think that should be taken out because it's not strictly necessary and is causing other issues in newer packages. 

We will work on this issue and report the fix in the release notes when it's done.

**Comment by kaicode** [comment]
Previous releases of Loinc are available here: https://loinc.org/downloads/archive/
