### ISSUE TITLE
Does Snowstorm implement all get resource api from hapi-fhir

### ISSUE THREAD

**Issue by TranLong183** [IHTSDO/snowstorm#535]
I read the doc and see Snowstorm iplement fhir api from hapi-fhir. So I try to get Patient list use the get resource api like 
```
<host>/fhir/Patient
```
and it return 404 not found that mean snowstorm just implement the some api like code-system ( and some resource in the docs ) right.
So that if I want to retrieve fhir resource I still have to build the hapi-fhir server on my own.

Thanks for helping.

**Comment by kaicode** [comment]
Yes that's right. Snowstorm is a FHIR Terminology Server rather than a general FHIR Server so it is not capable of holding patient records.

Snowstorm implements many of the resources of the [FHIR Terminology Module](https://www.hl7.org/fhir/terminology-module.html) including CodeSystem, ValueSet and ConceptMap. There is limited support for StructureDefinition.

There are other open source projects for the other FHIR resources like the [LinuxForHealth FHIR® Server](https://github.com/LinuxForHealth/FHIR) (formerly the IBM FHIR Server) the HAPI-FHIR Framework.

Often general purpose FHIR servers can be configured to delegate terminology specific functionality to a separate Terminology Server. It's recognised that this can be a specialist job, depending on the terminology functionality utilised.
