### ISSUE TITLE
Getting 'Bad Request - 'DELETE' method not supported' back from DELETE endpoint

### ISSUE THREAD

**Issue by ChrysmOre** [IHTSDO/snowstorm#57]
Getting 'Bad Request - request method 'DELETE' not supported' back 
when testing the delete concept endpoint?

**Comment by kaicode** [comment]
Hi @ChrysmOre,
You are probably getting:
```
{
  "error": "BAD_REQUEST",
  "message": "Released concept will not be deleted."
}
```
Snowstorm does not allow deleting concepts which have been released. This delete function is for when using Snowstorm is used as a SNOMED CT authoring server. In that scenario it is possible to create and then delete a concept before the end of the authoring cycle when the content is all versioned and released. If a released concept is no longer needed then it is made inactive by setting the active flag to false. In this scenario during authoring we have a set of screens in the authoring platform UI which finds and updates and relationships pointing to the concept being made inactive so that we don't end up with relationships pointing to inactive or missing concepts.

I hope that helps.

Kind regards, Kai
