### ISSUE TITLE
Search feature - slow response

### ISSUE THREAD

**Issue by MaxLmqr** [IHTSDO/snowstorm#581]
Hello !

# Summary

I am using a self-hosted snowstorm, with data correctly loaded. I'm using the api (following [this documentation](https://github.com/IHTSDO/snowstorm/blob/master/docs/search.md)) to perform concept based search, using ECL to restrict the scope of the search.

The search using both `ecl` and `term` parameters ends up in blocking snowstorm for a very long duration.

## Setup

Almalinux
Snowstorm release 9.2.0
elastic search 7.10.0

## Steps taken

Run elastic search
Load SNOMED concepts (currently `SnomedCT_InternationalRF2_PRODUCTION_20230331T120000Z.zip`)
Perform a search on the following endpoint : `/MAIN%2FSNOMEDCT-FR%2F2023-10-31/concepts?ecl=%3C404684003|Clinical%20finding|` 
Perform a search on the following endpoint : `/MAIN%2FSNOMEDCT-FR%2F2023-10-31/concepts?ecl=%3C404684003|Clinical%20finding|&term=aphasie` 

While the first query is around 100ms, the second triggers an operation in snowstorm which takes up to 60s. On the following queries, the operation is cached and results in sub 100ms results.

## Detailed exception
```
1|run_snowstorm  | 2024-01-30 20:07:23.272  INFO 5680 --- [nio-8080-exec-6] o.snomed.snowstorm.core.util.TimerUtil   : Timer ECL took more than 5 seconds.: ecl:'< 404684003 |Clinical finding|', with 120448 results in this page, now cached for this branch/commit/page. took 38.128 seconds
1|run_snowstorm  | 2024-01-30 20:07:23.275  INFO 5680 --- [nio-8080-exec-6] o.snomed.snowstorm.core.util.TimerUtil   : Timer Lexical and Logical Search: filtered logical complete took 38.131 seconds
1|run_snowstorm  | 2024-01-30 20:07:23.276  INFO 5680 --- [nio-8080-exec-6] o.s.s.core.data.services.QueryService    : 27 lexical results, 26 logical results
```

Do you have a suggestion on the step I could take from here to improve performance, or if I have made a mistake somewhere in the process.

Thank you,

**Comment by kaicode** [comment]
Hi @MaxLmqr,

This is expected behaviour, let me explain. Filtering an ECL result using text triggers aggressive caching in Snowstorm that collects all concept results exhaustively and keeps them in memory before applying the text filter. For the whole set of Clinical findings this is likely to take around 30 seconds. Subsequent calls using the same SNOMED version and ECL with _any_ text filter will be very fast.

I have implemented this technique because it is very common for a terminology server to be used to support data input where the search field is bound to a value set expressed using ECL. The user can use type-ahead style search to find the best matching results within the constrained set. 

I notice you are using the Snowstorm native API. I usually recommend using the FHIR API because this is part of a standard.
For example to expand ECL with a text filter: 
```
GET /fhir/ValueSet/$expand?url=http://snomed.info/sct?fhir_vs=ecl/%3C404684003|Clinical%20finding|&filter=aphasia
```

Also see [Snowstorm Lite](https://github.com/IHTSDO/snowstorm-lite) which offers a faster search and much lower memory requirements. Snowstorm Lite also supports fuzzy search by appending a tilde character to the filter string. An application could use this automatically if the first search returns nothing.

I hope this helps!

**Comment by MaxLmqr** [comment]
Hello,

Thank you for your explanations. I understand that this is expected behavior. I have noticed that the subsequent calls are very fast.

Does the usage of the FHIR API avoid the 30-second delay when using ECL?

To explain a bit more, we have users who can specify an ECL in our application. Then, we perform our research for the list of terms in their file, with that ECL specified.

An idea could be to make a first request with that ECL to store results, then perform the query list. However, I'm not fond of this since during the caching process, our browser is unable to load Snowstorm, which is disturbing the user experience. If the FHIR API is faster, I may use it instead of the native API. I will look into this solution. I will also check Snowstorm Lite. Do you also recommend using the FHIR API, or is the Native API faster? If you have a suggestion on the flow to follow, I'd be delighted too.

Best regards,

**Comment by kaicode** [comment]
The FHIR API uses the same caching technique. The initial delay could be avoided by priming the cache when the application starts by having a startup script make the call before any users or other applications do. Using an ECL query with a smaller set of results would also reduce the time needed to perform the caching step. If you do not know the ECL up front these options may be of limited use.

Snowstorm should not block other operations while running an expensive ECL query.

Snowstorm Lite is faster all round. It doesn't have an ECL cache because it's not necessary. It has a single index including the concept, ECL information and all concept terms. The ECL and text filtering can happen in one hit. It only has a FHIR API. The downsides are that Snowstorm Lite supports a subset of ECL functionality - just hierarchy operators and basic attribute constraints, no cardinality or filters. Snowstorm Lite also has a different search result sorting mechanism that is not quite as good as Snowstorm yet. It only has a FHIR API, this is unlikely to change. It runs really fast and only needs 1g of memory so it's fun to try.

**Comment by MaxLmqr** [comment]
The main issue was in our case that requests are executed in parallel, so the caching operation is run multiple times and ends up disturbing and at some point completely blocking Snowstorm. But with some tests, you are right and running one ECL request does not block other operations, so we should be fine.

We will modify the flow to first perform a caching step which will take around 30 second, then perform our research.

I will keep in mind Snowstorm Lite if our current plan doesn't suit our need !

Thank you very much, I think that this issue can be closed.

**Comment by kaicode** [comment]
Best of luck! We are here if you need anything.

**Comment by kaicode** [comment]
There is no timeout on the cache but be aware that there is a separate cache per CodeSystem and ECL query.
If the ECL query changes or the same query is run on a different CodeSystem (even different versions of the same SNOMED CT Edition), then the cache will be primed.

Information about the ECL cache is available using a GET request `/admin/cache/ecl/stats`.
The response is a list of the SNOMED Snowstorm version control branches that have anything cached. 
For each branch the following details are included:
- `size` shows the number of ECL queries that are cached for that branch
- the number of cache hits today
- the number of cache hits in the last 7 days
- the number of cache hits in the last 30 days

@ktadiko this information should help you keep track of which branches have some ECL queries primed.
