### ISSUE TITLE
What are the correct steps for loading a dailybuild file manually?

### ISSUE THREAD

**Issue by Skittlesbucket** [IHTSDO/snowstorm#627]
Hi,

We have an issue where after upgrading our codesystem (SNOMEDCT-NO) to a different dependant version, prior deactivated content is reactivated. NRC has been in contact with SI and they say all data is good on their side and I have been asked to load a DB file on the demo server to test there. The new file has a slightly newer timestamp than the one loaded during the night.

What would be the correct way to do this? I am assuming I have to upload the file to the correct folder on the server, but what about the file from the same date? Should I remove it? Should I do a dailybuild- or branch commit rollback?  Anything else?

Please advice!

**Comment by kaicode** [comment]
Before upgrading to a new dependant version it's important to disable the dailybuild automated import process and rollback the dailybuild import.
If you drop me an email in the next hour and we can jump on a call to resolve this on your server.

**Comment by kaicode** [comment]
I've just remembered that the dailybuild rollback is now automatic when upgrading a codesystem ([documented here](https://github.com/IHTSDO/snowstorm/blob/master/docs/daily-build-imports.md#other-behaviour-changes)). We shouldn't need a call because there should not be a data issue.

Snowstorm will automatically load a new dailybuild archive if there is one placed into the dailybuild source folder. The datestamp of the zip file must be newer than the latest commit on the SNOMEDCT-NO branch for the import to run. To see the current commit on the SNOMEDCT-NO branch use the `GET /branches/{branch}` endpoint. The head timestamp is the latest commit.
