### ISSUE TITLE
Sort LOINC codes during expand

### ISSUE THREAD

**Issue by albert-t25** [IHTSDO/snowstorm#643]
We have imported LOINC codes in Snowstorm and are trying to browse them using fhir/ValueSet/$expand?url=http://loinc.org?fhir_vs. However the returned codes are sorted in a default order and we would like to get them sorted by some other property, for example by "common test rank". Is that possible to do when using expand operation? If not, is there an alternative?

Thanks

**Comment by kaicode** [comment]
When just expanding a ValueSet LOINC codes without a filter results are sorted by code. This is not intended to be a useful order but it's deterministic so ensures correct pagination behaviour.

When expanding a ValueSet with a filter then a different sort is applied automatically, this is the display term length in ascending order. So the shortest matching display terms will come first. It might also be useful to apply alphabetical sorting so that matching terms of the same length come in some logical and deterministic order, but this has not been implemented yet.

It's not possible to apply a custom sort order. Feel free to fork the repository and implement this for non-SNOMED codesystems by following the standard FHIR conventions.
The sort order is currently set in the code [here](https://github.com/IHTSDO/snowstorm/blob/156021489260edd157e5c30934286904fbcbf152/src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java#L287).

**Comment by albert-t25** [comment]
Thank you @kaicode, appreciated
