### ISSUE TITLE
Question: Combining Austrian and German versions

### ISSUE THREAD

**Issue by albert-t25** [IHTSDO/snowstorm#645]
We have currently loaded German edition under MAIN/SNOMEDCT-DE branch and Austrian edition under MAIN/SNOMEDCT-AT. If we want to "combine" both, meaning get the translations in German from both, should we load Austrian under the German branch? Something like MAIN/SNOMEDCT-DE/SNOMEDCT-AT and then query against this branch?

Or are we looking at this from the wrong perspective?

Thanks

**Comment by kaicode** [comment]
To see content from both extensions at once you would have to load one on top of the other. Yes your `MAIN/SNOMEDCT-DE/SNOMEDCT-AT` suggestion would work.

**Just be careful with this approach** because the clinical concepts in the Austrian edition have not been classified together with the German edition. At this time there are only two clinical in the AT edition so it's unlikely that there are any fully-defined concepts in the DE edition that would have subsumbed them. 

This technique seems acceptable in this case.

**Comment by kaicode** [comment]
There are likely to be some duplicate terms with this approach. 

If you use the FHIR API you could use an ordered list of language refsets including the German Edition and Austrian Edition terms. This way the DE codesystem term will be used as the display term and the AT codesystem terms will be included in the set of synonyms that help find relevant term search results. 

For example: you could add a couple of language dialect aliases to Snowstorm like this:
```
# 31000274107 |Germany language reference set|
search.dialect.config.de-de=31000274107
# 21000234103 |Deutschsprachiges Referenzset Österreich|
search.dialect.config.de-at=21000234103
```
Then in a FHIR ValueSet expand request:
`displayLanguage=de-de,de-at`

Note that the displayLanguage parameter currently controls the display term **and** the search substrate. If only the DE codesystem language refset is requested then the AT codesystem terms will not be used to find matches.
