### ISSUE TITLE
Snowstorm handles CORS

### ISSUE THREAD

**Issue by StephanMeijer** [IHTSDO/snowstorm#70]
I am currently using Dokku / Nginx in combination with Snowstorm. The issue: Snowstorm handles my CORS request and sends back a `403` with the message `Invalid CORS Request`. How to make Snowstorm unresponsible for CORS-handling?

**Comment by StephanMeijer** [comment]
Possibly related; #25

**Comment by kaicode** [comment]
Hi @StephanMeijer,

We are using a Nginx configuration similar to https://gist.github.com/Stanback/7145487#gistcomment-2309997 which is working nicely for us.

We actually have `  proxy_set_header X-Forwarded-Host $host;` which I believe is telling Snowstorm/Spring-Boot that the request was made from the same IP as Nginx so the request is not recognised as cross-site. 

I am hesitant to add anything to do with CORS into Snowstorm directly because it's really a hosting concern and can all be handled in the http server.

Cheers,
Kai

**Comment by StephanMeijer** [comment]
Now trying this method.

**Comment by StephanMeijer** [comment]
Changed nginx config to contain:

```conf
    proxy_set_header X-Forwarded-Host $host;

    proxy_set_header 'Origin' '';
    proxy_set_header 'Access-Control-Request-Method' '';
    proxy_set_header 'Access-Control-Request-Headers' '';

    add_header 'Access-Control-Allow-Origin' 'http://localhost:8100' always;
```

Change header `Access-Control-Allow-Origin` accordingly to your needs.

**Comment by StephanMeijer** [comment]
Don't forget to set `Access-Control-Allow-Headers`
