### ISSUE TITLE
Wrong Spanish character folding default configuration

### ISSUE THREAD

**Issue by moraleja39** [IHTSDO/snowstorm#83]
After following the conversation in #41, I would say the unfolded characters configuration for the Spanish language implemeted in ce4d54aca9db4547b6381c5a40cd20d3acbb60c4 is not correct.

Snowstorm was returning undesired search results, and I found that to be the cause. In my opinion, the unfolded characters should be `üñ` (perhaps `ü` could be folded as well, that's up for discussion). However, and without a doubt, `áéíóú` must be **folded**.

After changing that param and rebuilding the description index, me and my doctor colleagues have been getting correct and predictable results.

Perhaps @alopezo should give their two cents on this.

**Comment by kaicode** [comment]
Hi @alopezo,

In #41 you stated:
> ... in spanish we would like to fold:
> áéíóúüñ

However @moraleja39 is not finding this optimal for his purposes. 

Have you received any other feedback on this matter? If you would like the configuration changed that's no problem, otherwise we could just leave the default and let others optimise for their own purposes with custom configuration.

Your guidance would be appreciated.

Kind regards,
Kai

**Comment by kaicode** [comment]
The default configuration follows Alejandro's specification. He has not come back with any update to that.

Anyone wishing to use the alternative configuration suggested by @moraleja39 can override the default configuration using:
```
# Spanish (Alternative)
search.language.charactersNotFolded.se=üñ
```
See [overriding the default configuration](https://github.com/IHTSDO/snowstorm/blob/master/docs/configuration-guide.md#override-the-defaults).

Because this can be configured locally and the existing configuration matches that suggested by staff from the Argentina Ministry of Health I will close this ticket for now.

**Comment by danka74** [comment]
# Spanish (Alternative)
search.language.charactersNotFolded.es=üñ

**Comment by kaicode** [comment]
Thanks for spotting my typo in the language code @danka74, I've corrected my comment above 😄

**Comment by alopezo** [comment]
Sorry @kaicode , @moraleja39 for my very late involvement on this thread 🤦🏻‍♂️

I’m very happy with the final implementation, in our case folding all listed characters is our clear preference, but it’s really nice to have the option to prevent some of them in the case some special use case appears.

**Comment by kaicode** [comment]
Thanks for confirming @alopezo! 😄

**Comment by kaicode** [comment]
@alopezo I think we may have implemented your requirements incorrectly...

You asked for the characters `áéíóúüñ` to be *folded* but we have added then to *not folded* list in configuration. 

This means that a search term `mecanica` will match nothing although there are around 600 descriptions containing the word `mecánica` in the Spanish Edition.

Are you suggesting that all Spanish characters should be *folded* for search purposes in SNOMED CT.

**Comment by kaicode** [comment]
@alopezo, @moraleja39 are there any Spanish characters which should _not_ be folded? Otherwise I will change the default configuration for the Spanish language to have exclusions to character folding.

**Comment by kaicode** [comment]
No movement on this. Closing.
