### ISSUE TITLE
Feature Request Give results ordered by minimal lenght

### ISSUE THREAD

**Issue by firsapsistemas** [IHTSDO/snowstorm#88]
SNOMED browser works giving minimal character lenght at first position. I thing SNOWSTORM should work in same way (we can rearrange results locally, but there are problems when paging!

Thanks for your attention

**Comment by kaicode** [comment]
Hi @firsapsistemas,

Snowstorm is the backend for the public SNOMED CT browser hosted by SNOMED International.

Yes Snowstorm sorts term search results by term length in an ascending order.

In the response from the browser format description search endpoint this is clear to see because the term matched is quoted: https://browser.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/2019-07-31/descriptions?term=heart&active=true&conceptActive=true

The concept search endpoint uses the same sorting although it's not quite so easy to spot what is happening. Here all descriptions are used to find the shortest term match but only the FSN of the concept is returned in the response. This can make it look like the sorting is not working when in fact the concept with the shortest matching description is being put at the top: https://browser.ihtsdotools.org/snowstorm/snomed-ct/MAIN%2F2019-07-31/concepts?term=heart&activeFilter=true&termActive=true

These are the only endpoints with term search functionally at this time. Appending a term parameter to other endpoints will not have any effect on the matching or sorting of results. See the Swagger API interface for a full list of API endpoints and their available parameters:
https://browser.ihtsdotools.org/snowstorm/snomed-ct/swagger-ui.html

I hope that helps. 
Kind regards,
Kai
