### ISSUE TITLE
how to import SnomedCT_Odontogram

### ISSUE THREAD

**Issue by liquid36** [IHTSDO/snowstorm#91]
Hi!
I want to import the SnomedCT Odontogram referenset. what step should i do? is it necessary to create a new codeSystem? 

Thanks.

**Comment by kaicode** [comment]
Hi @liquid36, it's really up to you and how you want to manage your Snowstorm instance. 

For something as simple as a reference set I would be tempted to import it directly onto MAIN after importing an Edition like the International Edition. The only downside with this approach is that the Odontogram reference set is dependant on the January 2018 International Edition, I'm not sure if any of the concepts it references have since been retired. For this reason it may be safer to create a new code system which is dependant on the 20180131 release date and import the reference set there. It really depends on your use case and if you need to use it in combination with the latest International release.

Let us know how you get on and if you learn anything, I've not tried this yet and others in the community may be interested.

Kind regards,
Kai

**Comment by kaicode** [comment]
Apologies, I've just found the latest version of the SNOMED CT Odontogram refset package released in July 2019. Importing directly into MAIN now looks like a good option!

**Comment by liquid36** [comment]
So, if i don't want to create a new code system, i must create an importer like this:

```
{
  "branchPath": "MAIN/SNOMEDCT-ES",
  "createCodeSystemVersion": false,
  "type": "SNAPSHOT"
}
```

**Comment by kaicode** [comment]
Yes, that would do it. Assuming you already have the Spanish Edition on that branch.

**Comment by liquid36** [comment]
Great! Thanks.
