### ISSUE TITLE
ECL not working.

### ISSUE THREAD

**Issue by kapoorabhish** [IHTSDO/snowstorm#94]
The endpoint specified in the API README [using-the-api.md](https://github.com/IHTSDO/snowstorm/blob/master/docs/using-the-api.md)
`Find concepts by ECL query: http://localhost:8080/MAIN/concepts?ecl=<404684003|Clinical finding|`

Is returning the results same as 
`http://localhost:8080/MAIN/concepts`

According to me it's not working. Please tell me if I am missing something.

PS. Why I reached to ECl? I want to get all the descendants of disorder(64572001) which are 75982 in number. But the descendants endpoint throws error after fetching 10,000 i.e. the scroll is not implemented.

**Comment by kaicode** [comment]
Hi @kapoorabhish,
Yes, your local results look unexpected. Your GET request looks fine. You can try the same request against the publicly accessible instance (for test and development only) - https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct

These requests give different totals:
- https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/concepts?limit=1
- [https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/2019-07-31/concepts?limit=1&ecl=<404684003|Clinical%20finding|](https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/concepts?limit=1&ecl=<404684003|Clinical%20finding|)
... I've limited to 1 item to skip to the total count. I have included the release date in the branch because we have daily build content on MAIN in the public instance.

You could check that your Snowstorm semantic Elasticsearch index built properly. You could use the Elasticsearch "cat API" to check the number of documents in the semantic index
`curl "localhost:9200/_cat/indices/*semantic?v"`

You should have at least 700,000 documents in the `docs.count` column. 
(There 350,830 active concepts in the July 2019 International Edition and each concept has two entries in that index, one for the stated form and one for the inferred form.)

**Comment by kapoorabhish** [comment]
Hi @kaicode ,
Thanks for the answer. I should have made some mistake earlier in doing the api call. After following your above mentioned example, I could get the result.

I ran the command `curl "localhost:9200/_cat/indices/*semantic?v"` on my Elasticsearch cluster and this is the output,
```
health status index    uuid                   pri rep docs.count docs.deleted store.size pri.store.size  
green  open   semantic DvmtWdXqSvuI3UoLfmc6NQ   1   0    4760283      1013937      2.8gb          2.8gb
```
4760283 is way higher than 700,000. FYI, I have indexed full latest data.

Now, coming to my actual problem, as mentioned in the initial question, what I really want to do is get all the descendants of a concept. Some concepts e.g. 64572001 (Disorder) are having 75982(as per latest indexed data in my ES cluster) descendants in total.
While keep changing the offset and keeping the limit constant, I can reach upto 10000 but after that I get `{"error":"BAD_REQUEST","message":"Maximum offset + page size is 10,000."}`.

I also tried to use param `searchAfter` but got no success.

https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/concepts?limit=10&ecl=%3C64572001&offset=10000&searchAfter=WzcyNjM5MjAwMV0=

I hope the `searchAfter` param is there having meaning same as it is meant in ES scroll API.

**Comment by mertenssander** [comment]
Hi @kapoorabhish , just a quick reply from my phone. I believe you should leave out the offset, like this https://snowstorm.ihtsdotools.org/snowstorm/snomed-ct/MAIN/concepts?limit=10&ecl=%3C64572001&searchAfter=WzcyNjM5MjAwMV0= , and use the searchafter from the result for the next request. On my GitHub there's a python client using this method in the ECL part of the client (findconcepts function I think) (bit messy but functional)

**Comment by kapoorabhish** [comment]
@mertenssander Thanks a lot for the reply. And it really solves my problem. 👍

**Comment by kapoorabhish** [comment]
Let me finish my process and test it my end. Will close the issue once done.

**Comment by mertenssander** [comment]
Glad to help! Hope it works - for reference, this is the relevant line in my client https://github.com/mertenssander/python_snowstorm_client/blob/39cc768339eb4f32c4ab70890a0e889f7d010b93/snowstorm_client.py#L329

**Comment by danka74** [comment]
Hi @kapoorabhish ,
FWIW I also have a snowstorm client test repo for your entertainment: https://github.com/danka74/snowstorm-client-test
I use RxJS to work around the paging limits. There are a few examples all using ECL and various filters for post processing the snowstorm results.
Cheers,
Daniel

**Comment by kapoorabhish** [comment]
@kaicode @mertenssander Thanks for the prompt support.
@danka74 thanks for sharing. Let me check it out.
